In [1]:
import pandas as pd

In [9]:
df = pd.read_csv('/Users/exam/Desktop/uber.csv')

In [10]:
df

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
0,1/1/2016 21:11,1/1/2016 21:17,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain
1,1/2/2016 1:25,1/2/2016 1:37,Business,Fort Pierce,Fort Pierce,5.0,NaN
2,1/2/2016 20:25,1/2/2016 20:38,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies
3,1/5/2016 17:31,1/5/2016 17:45,Business,Fort Pierce,Fort Pierce,4.7,Meeting
4,1/6/2016 14:42,1/6/2016 15:49,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit
5,1/6/2016 17:15,1/6/2016 17:19,Business,West Palm Beach,West Palm Beach,4.3,Meal/Entertain
6,1/6/2016 17:30,1/6/2016 17:35,Business,West Palm Beach,Palm Beach,7.1,Meeting
7,1/7/2016 13:27,1/7/2016 13:33,Business,Cary,Cary,0.8,Meeting
8,1/10/2016 8:05,1/10/2016 8:25,Business,Cary,Morrisville,8.3,Meeting
9,1/10/2016 12:17,1/10/2016 12:44,Business,Jamaica,New York,16.5,Customer Visit
10,1/10/2016 15:08,1/10/2016 15:51,Business,New York,Queens,10.8,Meeting
11,1/10/2016 18:18,1/10/2016 18:53,Business,Elmhurst,New York,7.5,Meeting
12,1/10/2016 19:12,1/10/2016 19:32,Business,Midtown,East Harlem,6.2,Meeting
13,1/11/2016 8:55,1/11/2016 9:21,Business,East Harlem,NoMad,6.4,Temporary Site
14,1/11/2016 11:56,1/11/2016 12:03,Business,Flatiron District,Midtown,1.6,Errand/Supplies
15,1/11/2016 13:32,1/11/2016 13:46,Business,Midtown,Midtown East,1.7,Meal/Entertain
16,1/11/2016 14:30,1/11/2016 14:43,Business,Midtown East,Midtown,1.9,Meal/Entertain
17,1/12/2016 12:33,1/12/2016 12:49,Business,Midtown,Hudson Square,1.9,Meal/Entertain
18,1/12/2016 12:53,1/12/2016 13:09,Business,Hudson Square,Lower Manhattan,4.0,Meal/Entertain
19,1/12/2016 14:42,1/12/2016 14:56,Business,Lower Manhattan,Hudson Square,1.8,Errand/Supplies
20,1/12/2016 15:13,1/12/2016 15:28,Business,Hudson Square,Hell's Kitchen,2.4,Customer Visit
21,1/12/2016 15:42,1/12/2016 15:54,Business,Hell's Kitchen,Midtown,2.0,Errand/Supplies
22,1/12/2016 16:02,1/12/2016 17:00,Business,New York,Queens County,15.1,Meeting
23,1/13/2016 13:54,1/13/2016 14:07,Business,Downtown,Gulfton,11.2,Meeting
24,1/13/2016 15:00,1/13/2016 15:28,Business,Gulfton,Downtown,11.8,Meeting
25,1/14/2016 16:29,1/14/2016 17:05,Business,Houston,Houston,21.9,Customer Visit
26,1/14/2016 21:39,1/14/2016 21:45,Business,Eagan Park,Jamestown Court,3.9,Errand/Supplies
27,1/15/2016 0:41,1/15/2016 1:01,Business,Morrisville,Cary,8.0,Errand/Supplies
28,1/15/2016 11:43,1/15/2016 12:03,Business,Cary,Durham,10.4,Meal/Entertain
29,1/15/2016 13:26,1/15/2016 13:44,Business,Durham,Cary,10.4,Meal/Entertain
...,...,...,...,...,...,...,...
1126,12/28/2016 11:42,12/28/2016 12:12,Business,Unknown Location,Kar?chi,10.4,Errand/Supplies
1127,12/28/2016 13:53,12/28/2016 14:01,Business,Kar?chi,Kar?chi,2.0,Errand/Supplies
1128,12/28/2016 15:04,12/28/2016 15:39,Business,Kar?chi,Unknown Location,8.5,Meal/Entertain
1129,12/28/2016 17:02,12/28/2016 17:16,Business,Unknown Location,Kar?chi,4.4,Errand/Supplies
1130,12/28/2016 18:33,12/28/2016 18:56,Business,Kar?chi,Kar?chi,3.8,Errand/Supplies
1131,12/28/2016 22:44,12/28/2016 23:18,Business,Kar?chi,Kar?chi,5.1,Errand/Supplies
1132,12/29/2016 0:49,12/29/2016 1:06,Business,Kar?chi,Kar?chi,3.8,Errand/Supplies
1133,12/29/2016 9:44,12/29/2016 10:07,Business,Kar?chi,Unknown Location,11.6,Meal/Entertain
1134,12/29/2016 11:28,12/29/2016 12:00,Business,Unknown Location,Kar?chi,11.9,Meal/Entertain
1135,12/29/2016 12:25,12/29/2016 12:33,Business,Kar?chi,Kar?chi,1.4,Errand/Supplies
1136,12/29/2016 13:17,12/29/2016 13:24,Business,Kar?chi,Kar?chi,1.1,Errand/Supplies
1137,12/29/2016 13:56,12/29/2016 14:11,Business,Kar?chi,Kar?chi,4.1,Airport/Travel
1138,12/29/2016 14:42,12/29/2016 14:58,Business,Kar?chi,Kar?chi,6.1,Between Offices
1139,12/29/2016 15:05,12/29/2016 15:16,Business,Kar?chi,Kar?chi,1.3,Errand/Supplies
1140,12/29/2016 18:59,12/29/2016 19:14,Business,Kar?chi,Unknown Location,3.0,Meal/Entertain
1141,12/29/2016 19:50,12/29/2016 20:10,Business,Unknown Location,Kar?chi,4.1,Customer Visit
1142,12/29/2016 20:15,12/29/2016 20:45,Business,Kar?chi,Kar?chi,7.2,Meeting
1143,12/29/2016 20:53,12/29/2016 21:42,Business,Kar?chi,Unknown Location,6.4,NaN
1144,12/29/2016 23:14,12/29/2016 23:47,Business,Unknown Location,Kar?chi,12.9,Meeting
1145,12/30/2016 10:15,12/30/2016 10:33,Business,Kar?chi,Kar?chi,2.8,Errand/Supplies
1146,12/30/2016 11:31,12/30/2016 11:56,Business,Kar?chi,Kar?chi,2.9,Errand/Supplies
1147,12/30/2016 15:41,12/30/2016 16:03,Business,Kar?chi,Kar?chi,4.6,Errand/Supplies
1148,12/30/2016 16:45,12/30/2016 17:08,Business,Kar?chi,Kar?chi,4.6,Meeting
1149,12/30/2016 23:06,12/30/2016 23:10,Business,Kar?chi,Kar?chi,0.8,Customer Visit
1150,12/31/2016 1:07,12/31/2016 1:14,Business,Kar?chi,Kar?chi,0.7,Meeting
1151,12/31/2016 13:24,12/31/2016 13:42,Business,Kar?chi,Unknown Location,3.9,Temporary Site
1152,12/31/2016 15:03,12/31/2016 15:38,Business,Unknown Location,Unknown Location,16.2,Meeting
1153,12/31/2016 21:32,12/31/2016 21:50,Business,Katunayake,Gampaha,6.4,Temporary Site
1154,12/31/2016 22:08,12/31/2016 23:51,Business,Gampaha,Ilukwatta,48.2,Temporary Site
1155,Totals,NaN,NaN,NaN,NaN,12204.7,NaN

In [12]:
df.describe()

             MILES*
count   1156.000000
mean      21.115398
std      359.299007
min        0.500000
25%        2.900000
50%        6.000000
75%       10.400000
max    12204.700000

In [11]:
df.shape()

TypeError: 'tuple' object is not callable

In [13]:
df.iloc[:,::2] #::2 will print every 2nd column

           START_DATE* CATEGORY*             STOP*         PURPOSE*
0       1/1/2016 21:11  Business       Fort Pierce   Meal/Entertain
1        1/2/2016 1:25  Business       Fort Pierce              NaN
2       1/2/2016 20:25  Business       Fort Pierce  Errand/Supplies
3       1/5/2016 17:31  Business       Fort Pierce          Meeting
4       1/6/2016 14:42  Business   West Palm Beach   Customer Visit
5       1/6/2016 17:15  Business   West Palm Beach   Meal/Entertain
6       1/6/2016 17:30  Business        Palm Beach          Meeting
7       1/7/2016 13:27  Business              Cary          Meeting
8       1/10/2016 8:05  Business       Morrisville          Meeting
9      1/10/2016 12:17  Business          New York   Customer Visit
10     1/10/2016 15:08  Business            Queens          Meeting
11     1/10/2016 18:18  Business          New York          Meeting
12     1/10/2016 19:12  Business       East Harlem          Meeting
13      1/11/2016 8:55  Business             NoMad   Temporary Site
14     1/11/2016 11:56  Business           Midtown  Errand/Supplies
15     1/11/2016 13:32  Business      Midtown East   Meal/Entertain
16     1/11/2016 14:30  Business           Midtown   Meal/Entertain
17     1/12/2016 12:33  Business     Hudson Square   Meal/Entertain
18     1/12/2016 12:53  Business   Lower Manhattan   Meal/Entertain
19     1/12/2016 14:42  Business     Hudson Square  Errand/Supplies
20     1/12/2016 15:13  Business    Hell's Kitchen   Customer Visit
21     1/12/2016 15:42  Business           Midtown  Errand/Supplies
22     1/12/2016 16:02  Business     Queens County          Meeting
23     1/13/2016 13:54  Business           Gulfton          Meeting
24     1/13/2016 15:00  Business          Downtown          Meeting
25     1/14/2016 16:29  Business           Houston   Customer Visit
26     1/14/2016 21:39  Business   Jamestown Court  Errand/Supplies
27      1/15/2016 0:41  Business              Cary  Errand/Supplies
28     1/15/2016 11:43  Business            Durham   Meal/Entertain
29     1/15/2016 13:26  Business              Cary   Meal/Entertain
...                ...       ...               ...              ...
1126  12/28/2016 11:42  Business           Kar?chi  Errand/Supplies
1127  12/28/2016 13:53  Business           Kar?chi  Errand/Supplies
1128  12/28/2016 15:04  Business  Unknown Location   Meal/Entertain
1129  12/28/2016 17:02  Business           Kar?chi  Errand/Supplies
1130  12/28/2016 18:33  Business           Kar?chi  Errand/Supplies
1131  12/28/2016 22:44  Business           Kar?chi  Errand/Supplies
1132   12/29/2016 0:49  Business           Kar?chi  Errand/Supplies
1133   12/29/2016 9:44  Business  Unknown Location   Meal/Entertain
1134  12/29/2016 11:28  Business           Kar?chi   Meal/Entertain
1135  12/29/2016 12:25  Business           Kar?chi  Errand/Supplies
1136  12/29/2016 13:17  Business           Kar?chi  Errand/Supplies
1137  12/29/2016 13:56  Business           Kar?chi   Airport/Travel
1138  12/29/2016 14:42  Business           Kar?chi  Between Offices
1139  12/29/2016 15:05  Business           Kar?chi  Errand/Supplies
1140  12/29/2016 18:59  Business  Unknown Location   Meal/Entertain
1141  12/29/2016 19:50  Business           Kar?chi   Customer Visit
1142  12/29/2016 20:15  Business           Kar?chi          Meeting
1143  12/29/2016 20:53  Business  Unknown Location              NaN
1144  12/29/2016 23:14  Business           Kar?chi          Meeting
1145  12/30/2016 10:15  Business           Kar?chi  Errand/Supplies
1146  12/30/2016 11:31  Business           Kar?chi  Errand/Supplies
1147  12/30/2016 15:41  Business           Kar?chi  Errand/Supplies
1148  12/30/2016 16:45  Business           Kar?chi          Meeting
1149  12/30/2016 23:06  Business           Kar?chi   Customer Visit
1150   12/31/2016 1:07  Business           Kar?chi          Meeting
1151  12/31/2016 13:24  Business  Unknown Location   Temporary Site
1152  12/31/2016 15:03  Business  Unknown Location          Meeting
1153  12/31/2016 21:32  Business           Gampaha   Temporary Site
1154  12/31/2016 22:08  Business         Ilukwatta   Temporary Site
1155            Totals       NaN               NaN              NaN

[1156 rows x 4 columns]

In [14]:
df.isnill()

AttributeError: 'DataFrame' object has no attribute 'isna'

In [16]:
df.isnull().sum()

START_DATE*      0
END_DATE*        1
CATEGORY*        1
START*           1
STOP*            1
MILES*           0
PURPOSE*       503
dtype: int64

In [17]:
df.isnull()

      START_DATE*  END_DATE*  CATEGORY*  START*  STOP*  MILES*  PURPOSE*
0           False      False      False   False  False   False     False
1           False      False      False   False  False   False      True
2           False      False      False   False  False   False     False
3           False      False      False   False  False   False     False
4           False      False      False   False  False   False     False
5           False      False      False   False  False   False     False
6           False      False      False   False  False   False     False
7           False      False      False   False  False   False     False
8           False      False      False   False  False   False     False
9           False      False      False   False  False   False     False
10          False      False      False   False  False   False     False
11          False      False      False   False  False   False     False
12          False      False      False   False  False   False     False
13          False      False      False   False  False   False     False
14          False      False      False   False  False   False     False
15          False      False      False   False  False   False     False
16          False      False      False   False  False   False     False
17          False      False      False   False  False   False     False
18          False      False      False   False  False   False     False
19          False      False      False   False  False   False     False
20          False      False      False   False  False   False     False
21          False      False      False   False  False   False     False
22          False      False      False   False  False   False     False
23          False      False      False   False  False   False     False
24          False      False      False   False  False   False     False
25          False      False      False   False  False   False     False
26          False      False      False   False  False   False     False
27          False      False      False   False  False   False     False
28          False      False      False   False  False   False     False
29          False      False      False   False  False   False     False
...           ...        ...        ...     ...    ...     ...       ...
1126        False      False      False   False  False   False     False
1127        False      False      False   False  False   False     False
1128        False      False      False   False  False   False     False
1129        False      False      False   False  False   False     False
1130        False      False      False   False  False   False     False
1131        False      False      False   False  False   False     False
1132        False      False      False   False  False   False     False
1133        False      False      False   False  False   False     False
1134        False      False      False   False  False   False     False
1135        False      False      False   False  False   False     False
1136        False      False      False   False  False   False     False
1137        False      False      False   False  False   False     False
1138        False      False      False   False  False   False     False
1139        False      False      False   False  False   False     False
1140        False      False      False   False  False   False     False
1141        False      False      False   False  False   False     False
1142        False      False      False   False  False   False     False
1143        False      False      False   False  False   False      True
1144        False      False      False   False  False   False     False
1145        False      False      False   False  False   False     False
1146        False      False      False   False  False   False     False
1147        False      False      False   False  False   False     False
1148        False      False      False   False  False   False     False
1149        False      False      False   False  False   False     False
1150        False      False      False   False  False   False     False
1151        False      False      False   False  False   False     False
1152        False      False      False   False  False   False     False
1153        False      False      False   False  False   False     False
1154        False      False      False   False  False   False     False
1155        False       True       True    True   True   False      True

[1156 rows x 7 columns]

In [18]:
dt=df.dropna(inplace=False)#it will delete every row with value false
#dt=df.dropna(inplace=True)--True will delete original

In [19]:
dt

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
0,1/1/2016 21:11,1/1/2016 21:17,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain
2,1/2/2016 20:25,1/2/2016 20:38,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies
3,1/5/2016 17:31,1/5/2016 17:45,Business,Fort Pierce,Fort Pierce,4.7,Meeting
4,1/6/2016 14:42,1/6/2016 15:49,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit
5,1/6/2016 17:15,1/6/2016 17:19,Business,West Palm Beach,West Palm Beach,4.3,Meal/Entertain
6,1/6/2016 17:30,1/6/2016 17:35,Business,West Palm Beach,Palm Beach,7.1,Meeting
7,1/7/2016 13:27,1/7/2016 13:33,Business,Cary,Cary,0.8,Meeting
8,1/10/2016 8:05,1/10/2016 8:25,Business,Cary,Morrisville,8.3,Meeting
9,1/10/2016 12:17,1/10/2016 12:44,Business,Jamaica,New York,16.5,Customer Visit
10,1/10/2016 15:08,1/10/2016 15:51,Business,New York,Queens,10.8,Meeting
11,1/10/2016 18:18,1/10/2016 18:53,Business,Elmhurst,New York,7.5,Meeting
12,1/10/2016 19:12,1/10/2016 19:32,Business,Midtown,East Harlem,6.2,Meeting
13,1/11/2016 8:55,1/11/2016 9:21,Business,East Harlem,NoMad,6.4,Temporary Site
14,1/11/2016 11:56,1/11/2016 12:03,Business,Flatiron District,Midtown,1.6,Errand/Supplies
15,1/11/2016 13:32,1/11/2016 13:46,Business,Midtown,Midtown East,1.7,Meal/Entertain
16,1/11/2016 14:30,1/11/2016 14:43,Business,Midtown East,Midtown,1.9,Meal/Entertain
17,1/12/2016 12:33,1/12/2016 12:49,Business,Midtown,Hudson Square,1.9,Meal/Entertain
18,1/12/2016 12:53,1/12/2016 13:09,Business,Hudson Square,Lower Manhattan,4.0,Meal/Entertain
19,1/12/2016 14:42,1/12/2016 14:56,Business,Lower Manhattan,Hudson Square,1.8,Errand/Supplies
20,1/12/2016 15:13,1/12/2016 15:28,Business,Hudson Square,Hell's Kitchen,2.4,Customer Visit
21,1/12/2016 15:42,1/12/2016 15:54,Business,Hell's Kitchen,Midtown,2.0,Errand/Supplies
22,1/12/2016 16:02,1/12/2016 17:00,Business,New York,Queens County,15.1,Meeting
23,1/13/2016 13:54,1/13/2016 14:07,Business,Downtown,Gulfton,11.2,Meeting
24,1/13/2016 15:00,1/13/2016 15:28,Business,Gulfton,Downtown,11.8,Meeting
25,1/14/2016 16:29,1/14/2016 17:05,Business,Houston,Houston,21.9,Customer Visit
26,1/14/2016 21:39,1/14/2016 21:45,Business,Eagan Park,Jamestown Court,3.9,Errand/Supplies
27,1/15/2016 0:41,1/15/2016 1:01,Business,Morrisville,Cary,8.0,Errand/Supplies
28,1/15/2016 11:43,1/15/2016 12:03,Business,Cary,Durham,10.4,Meal/Entertain
29,1/15/2016 13:26,1/15/2016 13:44,Business,Durham,Cary,10.4,Meal/Entertain
30,1/18/2016 14:55,1/18/2016 15:06,Business,Cary,Cary,4.8,Meal/Entertain
...,...,...,...,...,...,...,...
1124,12/27/2016 19:19,12/27/2016 19:50,Business,Kar?chi,Kar?chi,5.5,Customer Visit
1125,12/28/2016 8:34,12/28/2016 9:06,Business,Kar?chi,Unknown Location,10.3,Meal/Entertain
1126,12/28/2016 11:42,12/28/2016 12:12,Business,Unknown Location,Kar?chi,10.4,Errand/Supplies
1127,12/28/2016 13:53,12/28/2016 14:01,Business,Kar?chi,Kar?chi,2.0,Errand/Supplies
1128,12/28/2016 15:04,12/28/2016 15:39,Business,Kar?chi,Unknown Location,8.5,Meal/Entertain
1129,12/28/2016 17:02,12/28/2016 17:16,Business,Unknown Location,Kar?chi,4.4,Errand/Supplies
1130,12/28/2016 18:33,12/28/2016 18:56,Business,Kar?chi,Kar?chi,3.8,Errand/Supplies
1131,12/28/2016 22:44,12/28/2016 23:18,Business,Kar?chi,Kar?chi,5.1,Errand/Supplies
1132,12/29/2016 0:49,12/29/2016 1:06,Business,Kar?chi,Kar?chi,3.8,Errand/Supplies
1133,12/29/2016 9:44,12/29/2016 10:07,Business,Kar?chi,Unknown Location,11.6,Meal/Entertain
1134,12/29/2016 11:28,12/29/2016 12:00,Business,Unknown Location,Kar?chi,11.9,Meal/Entertain
1135,12/29/2016 12:25,12/29/2016 12:33,Business,Kar?chi,Kar?chi,1.4,Errand/Supplies
1136,12/29/2016 13:17,12/29/2016 13:24,Business,Kar?chi,Kar?chi,1.1,Errand/Supplies
1137,12/29/2016 13:56,12/29/2016 14:11,Business,Kar?chi,Kar?chi,4.1,Airport/Travel
1138,12/29/2016 14:42,12/29/2016 14:58,Business,Kar?chi,Kar?chi,6.1,Between Offices
1139,12/29/2016 15:05,12/29/2016 15:16,Business,Kar?chi,Kar?chi,1.3,Errand/Supplies
1140,12/29/2016 18:59,12/29/2016 19:14,Business,Kar?chi,Unknown Location,3.0,Meal/Entertain
1141,12/29/2016 19:50,12/29/2016 20:10,Business,Unknown Location,Kar?chi,4.1,Customer Visit
1142,12/29/2016 20:15,12/29/2016 20:45,Business,Kar?chi,Kar?chi,7.2,Meeting
1144,12/29/2016 23:14,12/29/2016 23:47,Business,Unknown Location,Kar?chi,12.9,Meeting
1145,12/30/2016 10:15,12/30/2016 10:33,Business,Kar?chi,Kar?chi,2.8,Errand/Supplies
1146,12/30/2016 11:31,12/30/2016 11:56,Business,Kar?chi,Kar?chi,2.9,Errand/Supplies
1147,12/30/2016 15:41,12/30/2016 16:03,Business,Kar?chi,Kar?chi,4.6,Errand/Supplies
1148,12/30/2016 16:45,12/30/2016 17:08,Business,Kar?chi,Kar?chi,4.6,Meeting
1149,12/30/2016 23:06,12/30/2016 23:10,Business,Kar?chi,Kar?chi,0.8,Customer Visit
1150,12/31/2016 1:07,12/31/2016 1:14,Business,Kar?chi,Kar?chi,0.7,Meeting
1151,12/31/2016 13:24,12/31/2016 13:42,Business,Kar?chi,Unknown Location,3.9,Temporary Site
1152,12/31/2016 15:03,12/31/2016 15:38,Business,Unknown Location,Unknown Location,16.2,Meeting
1153,12/31/2016 21:32,12/31/2016 21:50,Business,Katunayake,Gampaha,6.4,Temporary Site
1154,12/31/2016 22:08,12/31/2016 23:51,Business,Gampaha,Ilukwatta,48.2,Temporary Site

In [20]:
df['PURPOSE*'].dtype

dtype('O')

In [21]:
df['PURPOSE*'].values

array(['Meal/Entertain', nan, 'Errand/Supplies', ..., 'Temporary Site',
       'Temporary Site', nan], dtype=object)

In [22]:
#overwrited to meeting in purpose column
df['PURPOSE*']='Meeting'

In [23]:
df

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
0,1/1/2016 21:11,1/1/2016 21:17,Business,Fort Pierce,Fort Pierce,5.1,Meeting
1,1/2/2016 1:25,1/2/2016 1:37,Business,Fort Pierce,Fort Pierce,5.0,Meeting
2,1/2/2016 20:25,1/2/2016 20:38,Business,Fort Pierce,Fort Pierce,4.8,Meeting
3,1/5/2016 17:31,1/5/2016 17:45,Business,Fort Pierce,Fort Pierce,4.7,Meeting
4,1/6/2016 14:42,1/6/2016 15:49,Business,Fort Pierce,West Palm Beach,63.7,Meeting
5,1/6/2016 17:15,1/6/2016 17:19,Business,West Palm Beach,West Palm Beach,4.3,Meeting
6,1/6/2016 17:30,1/6/2016 17:35,Business,West Palm Beach,Palm Beach,7.1,Meeting
7,1/7/2016 13:27,1/7/2016 13:33,Business,Cary,Cary,0.8,Meeting
8,1/10/2016 8:05,1/10/2016 8:25,Business,Cary,Morrisville,8.3,Meeting
9,1/10/2016 12:17,1/10/2016 12:44,Business,Jamaica,New York,16.5,Meeting
10,1/10/2016 15:08,1/10/2016 15:51,Business,New York,Queens,10.8,Meeting
11,1/10/2016 18:18,1/10/2016 18:53,Business,Elmhurst,New York,7.5,Meeting
12,1/10/2016 19:12,1/10/2016 19:32,Business,Midtown,East Harlem,6.2,Meeting
13,1/11/2016 8:55,1/11/2016 9:21,Business,East Harlem,NoMad,6.4,Meeting
14,1/11/2016 11:56,1/11/2016 12:03,Business,Flatiron District,Midtown,1.6,Meeting
15,1/11/2016 13:32,1/11/2016 13:46,Business,Midtown,Midtown East,1.7,Meeting
16,1/11/2016 14:30,1/11/2016 14:43,Business,Midtown East,Midtown,1.9,Meeting
17,1/12/2016 12:33,1/12/2016 12:49,Business,Midtown,Hudson Square,1.9,Meeting
18,1/12/2016 12:53,1/12/2016 13:09,Business,Hudson Square,Lower Manhattan,4.0,Meeting
19,1/12/2016 14:42,1/12/2016 14:56,Business,Lower Manhattan,Hudson Square,1.8,Meeting
20,1/12/2016 15:13,1/12/2016 15:28,Business,Hudson Square,Hell's Kitchen,2.4,Meeting
21,1/12/2016 15:42,1/12/2016 15:54,Business,Hell's Kitchen,Midtown,2.0,Meeting
22,1/12/2016 16:02,1/12/2016 17:00,Business,New York,Queens County,15.1,Meeting
23,1/13/2016 13:54,1/13/2016 14:07,Business,Downtown,Gulfton,11.2,Meeting
24,1/13/2016 15:00,1/13/2016 15:28,Business,Gulfton,Downtown,11.8,Meeting
25,1/14/2016 16:29,1/14/2016 17:05,Business,Houston,Houston,21.9,Meeting
26,1/14/2016 21:39,1/14/2016 21:45,Business,Eagan Park,Jamestown Court,3.9,Meeting
27,1/15/2016 0:41,1/15/2016 1:01,Business,Morrisville,Cary,8.0,Meeting
28,1/15/2016 11:43,1/15/2016 12:03,Business,Cary,Durham,10.4,Meeting
29,1/15/2016 13:26,1/15/2016 13:44,Business,Durham,Cary,10.4,Meeting
...,...,...,...,...,...,...,...
1126,12/28/2016 11:42,12/28/2016 12:12,Business,Unknown Location,Kar?chi,10.4,Meeting
1127,12/28/2016 13:53,12/28/2016 14:01,Business,Kar?chi,Kar?chi,2.0,Meeting
1128,12/28/2016 15:04,12/28/2016 15:39,Business,Kar?chi,Unknown Location,8.5,Meeting
1129,12/28/2016 17:02,12/28/2016 17:16,Business,Unknown Location,Kar?chi,4.4,Meeting
1130,12/28/2016 18:33,12/28/2016 18:56,Business,Kar?chi,Kar?chi,3.8,Meeting
1131,12/28/2016 22:44,12/28/2016 23:18,Business,Kar?chi,Kar?chi,5.1,Meeting
1132,12/29/2016 0:49,12/29/2016 1:06,Business,Kar?chi,Kar?chi,3.8,Meeting
1133,12/29/2016 9:44,12/29/2016 10:07,Business,Kar?chi,Unknown Location,11.6,Meeting
1134,12/29/2016 11:28,12/29/2016 12:00,Business,Unknown Location,Kar?chi,11.9,Meeting
1135,12/29/2016 12:25,12/29/2016 12:33,Business,Kar?chi,Kar?chi,1.4,Meeting
1136,12/29/2016 13:17,12/29/2016 13:24,Business,Kar?chi,Kar?chi,1.1,Meeting
1137,12/29/2016 13:56,12/29/2016 14:11,Business,Kar?chi,Kar?chi,4.1,Meeting
1138,12/29/2016 14:42,12/29/2016 14:58,Business,Kar?chi,Kar?chi,6.1,Meeting
1139,12/29/2016 15:05,12/29/2016 15:16,Business,Kar?chi,Kar?chi,1.3,Meeting
1140,12/29/2016 18:59,12/29/2016 19:14,Business,Kar?chi,Unknown Location,3.0,Meeting
1141,12/29/2016 19:50,12/29/2016 20:10,Business,Unknown Location,Kar?chi,4.1,Meeting
1142,12/29/2016 20:15,12/29/2016 20:45,Business,Kar?chi,Kar?chi,7.2,Meeting
1143,12/29/2016 20:53,12/29/2016 21:42,Business,Kar?chi,Unknown Location,6.4,Meeting
1144,12/29/2016 23:14,12/29/2016 23:47,Business,Unknown Location,Kar?chi,12.9,Meeting
1145,12/30/2016 10:15,12/30/2016 10:33,Business,Kar?chi,Kar?chi,2.8,Meeting
1146,12/30/2016 11:31,12/30/2016 11:56,Business,Kar?chi,Kar?chi,2.9,Meeting
1147,12/30/2016 15:41,12/30/2016 16:03,Business,Kar?chi,Kar?chi,4.6,Meeting
1148,12/30/2016 16:45,12/30/2016 17:08,Business,Kar?chi,Kar?chi,4.6,Meeting
1149,12/30/2016 23:06,12/30/2016 23:10,Business,Kar?chi,Kar?chi,0.8,Meeting
1150,12/31/2016 1:07,12/31/2016 1:14,Business,Kar?chi,Kar?chi,0.7,Meeting
1151,12/31/2016 13:24,12/31/2016 13:42,Business,Kar?chi,Unknown Location,3.9,Meeting
1152,12/31/2016 15:03,12/31/2016 15:38,Business,Unknown Location,Unknown Location,16.2,Meeting
1153,12/31/2016 21:32,12/31/2016 21:50,Business,Katunayake,Gampaha,6.4,Meeting
1154,12/31/2016 22:08,12/31/2016 23:51,Business,Gampaha,Ilukwatta,48.2,Meeting
1155,Totals,NaN,NaN,NaN,NaN,12204.7,Meeting

In [44]:
#to find diff between start date and end date and their duration should be saved in new column called diff
#method-1
df[['START_DATE*','END_DATE*']] = df[['START_DATE*','END_DATE*']].apply(pd.to_datetime)
df['Difference'] = df['END_DATE*'] - df['START_DATE*']

ValueError: ('Unknown string format', 'occurred at index START_DATE*')

In [31]:
#to find diff between start date and end date and their duration should be saved in new column called diff
#method-2
from pandas import datetime
sdt = pd.to_datetime(df['START_DATE*'],errors='coerce')

In [32]:
sdt

0      2016-01-01 21:11:00
1      2016-01-02 01:25:00
2      2016-01-02 20:25:00
3      2016-01-05 17:31:00
4      2016-01-06 14:42:00
5      2016-01-06 17:15:00
6      2016-01-06 17:30:00
7      2016-01-07 13:27:00
8      2016-01-10 08:05:00
9      2016-01-10 12:17:00
10     2016-01-10 15:08:00
11     2016-01-10 18:18:00
12     2016-01-10 19:12:00
13     2016-01-11 08:55:00
14     2016-01-11 11:56:00
15     2016-01-11 13:32:00
16     2016-01-11 14:30:00
17     2016-01-12 12:33:00
18     2016-01-12 12:53:00
19     2016-01-12 14:42:00
20     2016-01-12 15:13:00
21     2016-01-12 15:42:00
22     2016-01-12 16:02:00
23     2016-01-13 13:54:00
24     2016-01-13 15:00:00
25     2016-01-14 16:29:00
26     2016-01-14 21:39:00
27     2016-01-15 00:41:00
28     2016-01-15 11:43:00
29     2016-01-15 13:26:00
               ...
1126   2016-12-28 11:42:00
1127   2016-12-28 13:53:00
1128   2016-12-28 15:04:00
1129   2016-12-28 17:02:00
1130   2016-12-28 18:33:00
1131   2016-12-28 22:44:00
1132   2016-12-29 00:49:00
1133   2016-12-29 09:44:00
1134   2016-12-29 11:28:00
1135   2016-12-29 12:25:00
1136   2016-12-29 13:17:00
1137   2016-12-29 13:56:00
1138   2016-12-29 14:42:00
1139   2016-12-29 15:05:00
1140   2016-12-29 18:59:00
1141   2016-12-29 19:50:00
1142   2016-12-29 20:15:00
1143   2016-12-29 20:53:00
1144   2016-12-29 23:14:00
1145   2016-12-30 10:15:00
1146   2016-12-30 11:31:00
1147   2016-12-30 15:41:00
1148   2016-12-30 16:45:00
1149   2016-12-30 23:06:00
1150   2016-12-31 01:07:00
1151   2016-12-31 13:24:00
1152   2016-12-31 15:03:00
1153   2016-12-31 21:32:00
1154   2016-12-31 22:08:00
1155                   NaT
Name: START_DATE*, Length: 1156, dtype: datetime64[ns]

In [33]:
edt = pd.to_datetime(df['END_DATE*'],errors='coerce')#coerce is used to ignore string errors in to_datetime

In [34]:
edt

0      2016-01-01 21:17:00
1      2016-01-02 01:37:00
2      2016-01-02 20:38:00
3      2016-01-05 17:45:00
4      2016-01-06 15:49:00
5      2016-01-06 17:19:00
6      2016-01-06 17:35:00
7      2016-01-07 13:33:00
8      2016-01-10 08:25:00
9      2016-01-10 12:44:00
10     2016-01-10 15:51:00
11     2016-01-10 18:53:00
12     2016-01-10 19:32:00
13     2016-01-11 09:21:00
14     2016-01-11 12:03:00
15     2016-01-11 13:46:00
16     2016-01-11 14:43:00
17     2016-01-12 12:49:00
18     2016-01-12 13:09:00
19     2016-01-12 14:56:00
20     2016-01-12 15:28:00
21     2016-01-12 15:54:00
22     2016-01-12 17:00:00
23     2016-01-13 14:07:00
24     2016-01-13 15:28:00
25     2016-01-14 17:05:00
26     2016-01-14 21:45:00
27     2016-01-15 01:01:00
28     2016-01-15 12:03:00
29     2016-01-15 13:44:00
               ...
1126   2016-12-28 12:12:00
1127   2016-12-28 14:01:00
1128   2016-12-28 15:39:00
1129   2016-12-28 17:16:00
1130   2016-12-28 18:56:00
1131   2016-12-28 23:18:00
1132   2016-12-29 01:06:00
1133   2016-12-29 10:07:00
1134   2016-12-29 12:00:00
1135   2016-12-29 12:33:00
1136   2016-12-29 13:24:00
1137   2016-12-29 14:11:00
1138   2016-12-29 14:58:00
1139   2016-12-29 15:16:00
1140   2016-12-29 19:14:00
1141   2016-12-29 20:10:00
1142   2016-12-29 20:45:00
1143   2016-12-29 21:42:00
1144   2016-12-29 23:47:00
1145   2016-12-30 10:33:00
1146   2016-12-30 11:56:00
1147   2016-12-30 16:03:00
1148   2016-12-30 17:08:00
1149   2016-12-30 23:10:00
1150   2016-12-31 01:14:00
1151   2016-12-31 13:42:00
1152   2016-12-31 15:38:00
1153   2016-12-31 21:50:00
1154   2016-12-31 23:51:00
1155                   NaT
Name: END_DATE*, Length: 1156, dtype: datetime64[ns]

In [35]:
df['diff']=edt-sdt

In [38]:
df['diff']
df

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*,diff
0,1/1/2016 21:11,1/1/2016 21:17,Business,Fort Pierce,Fort Pierce,5.1,Meeting,00:06:00
1,1/2/2016 1:25,1/2/2016 1:37,Business,Fort Pierce,Fort Pierce,5.0,Meeting,00:12:00
2,1/2/2016 20:25,1/2/2016 20:38,Business,Fort Pierce,Fort Pierce,4.8,Meeting,00:13:00
3,1/5/2016 17:31,1/5/2016 17:45,Business,Fort Pierce,Fort Pierce,4.7,Meeting,00:14:00
4,1/6/2016 14:42,1/6/2016 15:49,Business,Fort Pierce,West Palm Beach,63.7,Meeting,01:07:00
5,1/6/2016 17:15,1/6/2016 17:19,Business,West Palm Beach,West Palm Beach,4.3,Meeting,00:04:00
6,1/6/2016 17:30,1/6/2016 17:35,Business,West Palm Beach,Palm Beach,7.1,Meeting,00:05:00
7,1/7/2016 13:27,1/7/2016 13:33,Business,Cary,Cary,0.8,Meeting,00:06:00
8,1/10/2016 8:05,1/10/2016 8:25,Business,Cary,Morrisville,8.3,Meeting,00:20:00
9,1/10/2016 12:17,1/10/2016 12:44,Business,Jamaica,New York,16.5,Meeting,00:27:00
10,1/10/2016 15:08,1/10/2016 15:51,Business,New York,Queens,10.8,Meeting,00:43:00
11,1/10/2016 18:18,1/10/2016 18:53,Business,Elmhurst,New York,7.5,Meeting,00:35:00
12,1/10/2016 19:12,1/10/2016 19:32,Business,Midtown,East Harlem,6.2,Meeting,00:20:00
13,1/11/2016 8:55,1/11/2016 9:21,Business,East Harlem,NoMad,6.4,Meeting,00:26:00
14,1/11/2016 11:56,1/11/2016 12:03,Business,Flatiron District,Midtown,1.6,Meeting,00:07:00
15,1/11/2016 13:32,1/11/2016 13:46,Business,Midtown,Midtown East,1.7,Meeting,00:14:00
16,1/11/2016 14:30,1/11/2016 14:43,Business,Midtown East,Midtown,1.9,Meeting,00:13:00
17,1/12/2016 12:33,1/12/2016 12:49,Business,Midtown,Hudson Square,1.9,Meeting,00:16:00
18,1/12/2016 12:53,1/12/2016 13:09,Business,Hudson Square,Lower Manhattan,4.0,Meeting,00:16:00
19,1/12/2016 14:42,1/12/2016 14:56,Business,Lower Manhattan,Hudson Square,1.8,Meeting,00:14:00
20,1/12/2016 15:13,1/12/2016 15:28,Business,Hudson Square,Hell's Kitchen,2.4,Meeting,00:15:00
21,1/12/2016 15:42,1/12/2016 15:54,Business,Hell's Kitchen,Midtown,2.0,Meeting,00:12:00
22,1/12/2016 16:02,1/12/2016 17:00,Business,New York,Queens County,15.1,Meeting,00:58:00
23,1/13/2016 13:54,1/13/2016 14:07,Business,Downtown,Gulfton,11.2,Meeting,00:13:00
24,1/13/2016 15:00,1/13/2016 15:28,Business,Gulfton,Downtown,11.8,Meeting,00:28:00
25,1/14/2016 16:29,1/14/2016 17:05,Business,Houston,Houston,21.9,Meeting,00:36:00
26,1/14/2016 21:39,1/14/2016 21:45,Business,Eagan Park,Jamestown Court,3.9,Meeting,00:06:00
27,1/15/2016 0:41,1/15/2016 1:01,Business,Morrisville,Cary,8.0,Meeting,00:20:00
28,1/15/2016 11:43,1/15/2016 12:03,Business,Cary,Durham,10.4,Meeting,00:20:00
29,1/15/2016 13:26,1/15/2016 13:44,Business,Durham,Cary,10.4,Meeting,00:18:00
...,...,...,...,...,...,...,...,...
1126,12/28/2016 11:42,12/28/2016 12:12,Business,Unknown Location,Kar?chi,10.4,Meeting,00:30:00
1127,12/28/2016 13:53,12/28/2016 14:01,Business,Kar?chi,Kar?chi,2.0,Meeting,00:08:00
1128,12/28/2016 15:04,12/28/2016 15:39,Business,Kar?chi,Unknown Location,8.5,Meeting,00:35:00
1129,12/28/2016 17:02,12/28/2016 17:16,Business,Unknown Location,Kar?chi,4.4,Meeting,00:14:00
1130,12/28/2016 18:33,12/28/2016 18:56,Business,Kar?chi,Kar?chi,3.8,Meeting,00:23:00
1131,12/28/2016 22:44,12/28/2016 23:18,Business,Kar?chi,Kar?chi,5.1,Meeting,00:34:00
1132,12/29/2016 0:49,12/29/2016 1:06,Business,Kar?chi,Kar?chi,3.8,Meeting,00:17:00
1133,12/29/2016 9:44,12/29/2016 10:07,Business,Kar?chi,Unknown Location,11.6,Meeting,00:23:00
1134,12/29/2016 11:28,12/29/2016 12:00,Business,Unknown Location,Kar?chi,11.9,Meeting,00:32:00
1135,12/29/2016 12:25,12/29/2016 12:33,Business,Kar?chi,Kar?chi,1.4,Meeting,00:08:00
1136,12/29/2016 13:17,12/29/2016 13:24,Business,Kar?chi,Kar?chi,1.1,Meeting,00:07:00
1137,12/29/2016 13:56,12/29/2016 14:11,Business,Kar?chi,Kar?chi,4.1,Meeting,00:15:00
1138,12/29/2016 14:42,12/29/2016 14:58,Business,Kar?chi,Kar?chi,6.1,Meeting,00:16:00
1139,12/29/2016 15:05,12/29/2016 15:16,Business,Kar?chi,Kar?chi,1.3,Meeting,00:11:00
1140,12/29/2016 18:59,12/29/2016 19:14,Business,Kar?chi,Unknown Location,3.0,Meeting,00:15:00
1141,12/29/2016 19:50,12/29/2016 20:10,Business,Unknown Location,Kar?chi,4.1,Meeting,00:20:00
1142,12/29/2016 20:15,12/29/2016 20:45,Business,Kar?chi,Kar?chi,7.2,Meeting,00:30:00
1143,12/29/2016 20:53,12/29/2016 21:42,Business,Kar?chi,Unknown Location,6.4,Meeting,00:49:00
1144,12/29/2016 23:14,12/29/2016 23:47,Business,Unknown Location,Kar?chi,12.9,Meeting,00:33:00
1145,12/30/2016 10:15,12/30/2016 10:33,Business,Kar?chi,Kar?chi,2.8,Meeting,00:18:00
1146,12/30/2016 11:31,12/30/2016 11:56,Business,Kar?chi,Kar?chi,2.9,Meeting,00:25:00
1147,12/30/2016 15:41,12/30/2016 16:03,Business,Kar?chi,Kar?chi,4.6,Meeting,00:22:00
1148,12/30/2016 16:45,12/30/2016 17:08,Business,Kar?chi,Kar?chi,4.6,Meeting,00:23:00
1149,12/30/2016 23:06,12/30/2016 23:10,Business,Kar?chi,Kar?chi,0.8,Meeting,00:04:00
1150,12/31/2016 1:07,12/31/2016 1:14,Business,Kar?chi,Kar?chi,0.7,Meeting,00:07:00
1151,12/31/2016 13:24,12/31/2016 13:42,Business,Kar?chi,Unknown Location,3.9,Meeting,00:18:00
1152,12/31/2016 15:03,12/31/2016 15:38,Business,Unknown Location,Unknown Location,16.2,Meeting,00:35:00
1153,12/31/2016 21:32,12/31/2016 21:50,Business,Katunayake,Gampaha,6.4,Meeting,00:18:00
1154,12/31/2016 22:08,12/31/2016 23:51,Business,Gampaha,Ilukwatta,48.2,Meeting,01:43:00
1155,Totals,NaN,NaN,NaN,NaN,12204.7,Meeting,NaT

In [39]:
#new column added named status with values completed
df['Status']='Completed'

In [40]:
df

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*,diff,Status
0,1/1/2016 21:11,1/1/2016 21:17,Business,Fort Pierce,Fort Pierce,5.1,Meeting,00:06:00,Completed
1,1/2/2016 1:25,1/2/2016 1:37,Business,Fort Pierce,Fort Pierce,5.0,Meeting,00:12:00,Completed
2,1/2/2016 20:25,1/2/2016 20:38,Business,Fort Pierce,Fort Pierce,4.8,Meeting,00:13:00,Completed
3,1/5/2016 17:31,1/5/2016 17:45,Business,Fort Pierce,Fort Pierce,4.7,Meeting,00:14:00,Completed
4,1/6/2016 14:42,1/6/2016 15:49,Business,Fort Pierce,West Palm Beach,63.7,Meeting,01:07:00,Completed
5,1/6/2016 17:15,1/6/2016 17:19,Business,West Palm Beach,West Palm Beach,4.3,Meeting,00:04:00,Completed
6,1/6/2016 17:30,1/6/2016 17:35,Business,West Palm Beach,Palm Beach,7.1,Meeting,00:05:00,Completed
7,1/7/2016 13:27,1/7/2016 13:33,Business,Cary,Cary,0.8,Meeting,00:06:00,Completed
8,1/10/2016 8:05,1/10/2016 8:25,Business,Cary,Morrisville,8.3,Meeting,00:20:00,Completed
9,1/10/2016 12:17,1/10/2016 12:44,Business,Jamaica,New York,16.5,Meeting,00:27:00,Completed
10,1/10/2016 15:08,1/10/2016 15:51,Business,New York,Queens,10.8,Meeting,00:43:00,Completed
11,1/10/2016 18:18,1/10/2016 18:53,Business,Elmhurst,New York,7.5,Meeting,00:35:00,Completed
12,1/10/2016 19:12,1/10/2016 19:32,Business,Midtown,East Harlem,6.2,Meeting,00:20:00,Completed
13,1/11/2016 8:55,1/11/2016 9:21,Business,East Harlem,NoMad,6.4,Meeting,00:26:00,Completed
14,1/11/2016 11:56,1/11/2016 12:03,Business,Flatiron District,Midtown,1.6,Meeting,00:07:00,Completed
15,1/11/2016 13:32,1/11/2016 13:46,Business,Midtown,Midtown East,1.7,Meeting,00:14:00,Completed
16,1/11/2016 14:30,1/11/2016 14:43,Business,Midtown East,Midtown,1.9,Meeting,00:13:00,Completed
17,1/12/2016 12:33,1/12/2016 12:49,Business,Midtown,Hudson Square,1.9,Meeting,00:16:00,Completed
18,1/12/2016 12:53,1/12/2016 13:09,Business,Hudson Square,Lower Manhattan,4.0,Meeting,00:16:00,Completed
19,1/12/2016 14:42,1/12/2016 14:56,Business,Lower Manhattan,Hudson Square,1.8,Meeting,00:14:00,Completed
20,1/12/2016 15:13,1/12/2016 15:28,Business,Hudson Square,Hell's Kitchen,2.4,Meeting,00:15:00,Completed
21,1/12/2016 15:42,1/12/2016 15:54,Business,Hell's Kitchen,Midtown,2.0,Meeting,00:12:00,Completed
22,1/12/2016 16:02,1/12/2016 17:00,Business,New York,Queens County,15.1,Meeting,00:58:00,Completed
23,1/13/2016 13:54,1/13/2016 14:07,Business,Downtown,Gulfton,11.2,Meeting,00:13:00,Completed
24,1/13/2016 15:00,1/13/2016 15:28,Business,Gulfton,Downtown,11.8,Meeting,00:28:00,Completed
25,1/14/2016 16:29,1/14/2016 17:05,Business,Houston,Houston,21.9,Meeting,00:36:00,Completed
26,1/14/2016 21:39,1/14/2016 21:45,Business,Eagan Park,Jamestown Court,3.9,Meeting,00:06:00,Completed
27,1/15/2016 0:41,1/15/2016 1:01,Business,Morrisville,Cary,8.0,Meeting,00:20:00,Completed
28,1/15/2016 11:43,1/15/2016 12:03,Business,Cary,Durham,10.4,Meeting,00:20:00,Completed
29,1/15/2016 13:26,1/15/2016 13:44,Business,Durham,Cary,10.4,Meeting,00:18:00,Completed
...,...,...,...,...,...,...,...,...,...
1126,12/28/2016 11:42,12/28/2016 12:12,Business,Unknown Location,Kar?chi,10.4,Meeting,00:30:00,Completed
1127,12/28/2016 13:53,12/28/2016 14:01,Business,Kar?chi,Kar?chi,2.0,Meeting,00:08:00,Completed
1128,12/28/2016 15:04,12/28/2016 15:39,Business,Kar?chi,Unknown Location,8.5,Meeting,00:35:00,Completed
1129,12/28/2016 17:02,12/28/2016 17:16,Business,Unknown Location,Kar?chi,4.4,Meeting,00:14:00,Completed
1130,12/28/2016 18:33,12/28/2016 18:56,Business,Kar?chi,Kar?chi,3.8,Meeting,00:23:00,Completed
1131,12/28/2016 22:44,12/28/2016 23:18,Business,Kar?chi,Kar?chi,5.1,Meeting,00:34:00,Completed
1132,12/29/2016 0:49,12/29/2016 1:06,Business,Kar?chi,Kar?chi,3.8,Meeting,00:17:00,Completed
1133,12/29/2016 9:44,12/29/2016 10:07,Business,Kar?chi,Unknown Location,11.6,Meeting,00:23:00,Completed
1134,12/29/2016 11:28,12/29/2016 12:00,Business,Unknown Location,Kar?chi,11.9,Meeting,00:32:00,Completed
1135,12/29/2016 12:25,12/29/2016 12:33,Business,Kar?chi,Kar?chi,1.4,Meeting,00:08:00,Completed
1136,12/29/2016 13:17,12/29/2016 13:24,Business,Kar?chi,Kar?chi,1.1,Meeting,00:07:00,Completed
1137,12/29/2016 13:56,12/29/2016 14:11,Business,Kar?chi,Kar?chi,4.1,Meeting,00:15:00,Completed
1138,12/29/2016 14:42,12/29/2016 14:58,Business,Kar?chi,Kar?chi,6.1,Meeting,00:16:00,Completed
1139,12/29/2016 15:05,12/29/2016 15:16,Business,Kar?chi,Kar?chi,1.3,Meeting,00:11:00,Completed
1140,12/29/2016 18:59,12/29/2016 19:14,Business,Kar?chi,Unknown Location,3.0,Meeting,00:15:00,Completed
1141,12/29/2016 19:50,12/29/2016 20:10,Business,Unknown Location,Kar?chi,4.1,Meeting,00:20:00,Completed
1142,12/29/2016 20:15,12/29/2016 20:45,Business,Kar?chi,Kar?chi,7.2,Meeting,00:30:00,Completed
1143,12/29/2016 20:53,12/29/2016 21:42,Business,Kar?chi,Unknown Location,6.4,Meeting,00:49:00,Completed
1144,12/29/2016 23:14,12/29/2016 23:47,Business,Unknown Location,Kar?chi,12.9,Meeting,00:33:00,Completed
1145,12/30/2016 10:15,12/30/2016 10:33,Business,Kar?chi,Kar?chi,2.8,Meeting,00:18:00,Completed
1146,12/30/2016 11:31,12/30/2016 11:56,Business,Kar?chi,Kar?chi,2.9,Meeting,00:25:00,Completed
1147,12/30/2016 15:41,12/30/2016 16:03,Business,Kar?chi,Kar?chi,4.6,Meeting,00:22:00,Completed
1148,12/30/2016 16:45,12/30/2016 17:08,Business,Kar?chi,Kar?chi,4.6,Meeting,00:23:00,Completed
1149,12/30/2016 23:06,12/30/2016 23:10,Business,Kar?chi,Kar?chi,0.8,Meeting,00:04:00,Completed
1150,12/31/2016 1:07,12/31/2016 1:14,Business,Kar?chi,Kar?chi,0.7,Meeting,00:07:00,Completed
1151,12/31/2016 13:24,12/31/2016 13:42,Business,Kar?chi,Unknown Location,3.9,Meeting,00:18:00,Completed
1152,12/31/2016 15:03,12/31/2016 15:38,Business,Unknown Location,Unknown Location,16.2,Meeting,00:35:00,Completed
1153,12/31/2016 21:32,12/31/2016 21:50,Business,Katunayake,Gampaha,6.4,Meeting,00:18:00,Completed
1154,12/31/2016 22:08,12/31/2016 23:51,Business,Gampaha,Ilukwatta,48.2,Meeting,01:43:00,Completed
1155,Totals,NaN,NaN,NaN,NaN,12204.7,Meeting,NaT,Completed

In [51]:
del df['diff']#deletes the column

In [52]:
#will return the name of the columns present in given csv file
df.columns

Index(['START_DATE*', 'END_DATE*', 'CATEGORY*', 'START*', 'STOP*', 'MILES*',
       'PURPOSE*', 'Status'],
      dtype='object')

In [53]:
#will print miles greater than 5
dm = df[df['MILES*'] > 5]
print('Resulted Miles :', dm)

Resulted Miles :            START_DATE*         END_DATE* CATEGORY*               START*  \
0       1/1/2016 21:11    1/1/2016 21:17  Business          Fort Pierce
4       1/6/2016 14:42    1/6/2016 15:49  Business          Fort Pierce
6       1/6/2016 17:30    1/6/2016 17:35  Business      West Palm Beach
8       1/10/2016 8:05    1/10/2016 8:25  Business                 Cary
9      1/10/2016 12:17   1/10/2016 12:44  Business              Jamaica
10     1/10/2016 15:08   1/10/2016 15:51  Business             New York
11     1/10/2016 18:18   1/10/2016 18:53  Business             Elmhurst
12     1/10/2016 19:12   1/10/2016 19:32  Business              Midtown
13      1/11/2016 8:55    1/11/2016 9:21  Business          East Harlem
22     1/12/2016 16:02   1/12/2016 17:00  Business             New York
23     1/13/2016 13:54   1/13/2016 14:07  Business             Downtown
24     1/13/2016 15:00   1/13/2016 15:28  Business              Gulfton
25     1/14/2016 16:29   1/14/2016 17:05  Business              Houston
27      1/15/2016 0:41    1/15/2016 1:01  Business          Morrisville
28     1/15/2016 11:43   1/15/2016 12:03  Business                 Cary
29     1/15/2016 13:26   1/15/2016 13:44  Business               Durham
32      1/19/2016 9:09    1/19/2016 9:23  Business          Whitebridge
33     1/19/2016 10:55   1/19/2016 11:09  Business  Lake Wellingborough
34     1/20/2016 10:36   1/20/2016 11:11  Business                 Cary
35     1/20/2016 11:48   1/20/2016 12:19  Business  Fayetteville Street
36     1/20/2016 13:25   1/20/2016 14:19  Business              Raleigh
46     1/27/2016 10:19   1/27/2016 10:48  Business                 Cary
49     1/27/2016 14:46   1/27/2016 15:08  Business              Raleigh
50     1/28/2016 12:28   1/28/2016 13:00  Business                 Cary
51     1/28/2016 15:11   1/28/2016 15:31  Business      Meredith Townes
52     1/28/2016 16:21   1/28/2016 16:51  Business              Raleigh
54     1/29/2016 10:56   1/29/2016 11:07  Business                 Cary
55     1/29/2016 11:43   1/29/2016 12:03  Business                 Cary
56     1/29/2016 13:24   1/29/2016 13:47  Business               Durham
57     1/29/2016 18:31   1/29/2016 18:52  Business                 Cary
...                ...               ...       ...                  ...
1090  12/22/2016 17:04  12/22/2016 17:20  Business     Unknown Location
1091  12/22/2016 17:27  12/22/2016 17:53  Business     Unknown Location
1092  12/22/2016 17:56  12/22/2016 18:29  Business     Unknown Location
1094  12/22/2016 18:38  12/22/2016 18:47  Business     Unknown Location
1095  12/22/2016 19:04  12/22/2016 19:50  Business     Unknown Location
1099  12/23/2016 11:33  12/23/2016 11:58  Business               Lahore
1100  12/23/2016 14:15  12/23/2016 15:25  Business     Unknown Location
1102  12/23/2016 17:34  12/23/2016 18:27  Business     Unknown Location
1103   12/24/2016 7:43   12/24/2016 8:04  Business               Lahore
1104   12/24/2016 9:19   12/24/2016 9:55  Business     Unknown Location
1105  12/24/2016 10:34  12/24/2016 10:53  Business               Lahore
1115   12/26/2016 9:05   12/26/2016 9:19  Business               Lahore
1116  12/26/2016 10:15  12/26/2016 10:36  Business               Lahore
1118  12/26/2016 13:09  12/26/2016 13:43  Business               Lahore
1123  12/27/2016 16:34  12/27/2016 16:58  Business     Unknown Location
1124  12/27/2016 19:19  12/27/2016 19:50  Business              Kar?chi
1125   12/28/2016 8:34   12/28/2016 9:06  Business              Kar?chi
1126  12/28/2016 11:42  12/28/2016 12:12  Business     Unknown Location
1128  12/28/2016 15:04  12/28/2016 15:39  Business              Kar?chi
1131  12/28/2016 22:44  12/28/2016 23:18  Business              Kar?chi
1133   12/29/2016 9:44  12/29/2016 10:07  Business              Kar?chi
1134  12/29/2016 11:28  12/29/2016 12:00  Business     Unknown Location
1138  12/29/2016 14:42  12/29/2016 14:58  Business              Kar?chi
1142  12/29/2016 20:15  12/29/2016 20:45  Business              Kar?chi
1143  12/29/2016 20:53  12/29/2016 21:42  Business              Kar?chi
1144  12/29/2016 23:14  12/29/2016 23:47  Business     Unknown Location
1152  12/31/2016 15:03  12/31/2016 15:38  Business     Unknown Location
1153  12/31/2016 21:32  12/31/2016 21:50  Business           Katunayake
1154  12/31/2016 22:08  12/31/2016 23:51  Business              Gampaha
1155            Totals               NaN       NaN                  NaN

                    STOP*   MILES* PURPOSE*     Status
0             Fort Pierce      5.1  Meeting  Completed
4         West Palm Beach     63.7  Meeting  Completed
6              Palm Beach      7.1  Meeting  Completed
8             Morrisville      8.3  Meeting  Completed
9                New York     16.5  Meeting  Completed
10                 Queens     10.8  Meeting  Completed
11               New York      7.5  Meeting  Completed
12            East Harlem      6.2  Meeting  Completed
13                  NoMad      6.4  Meeting  Completed
22          Queens County     15.1  Meeting  Completed
23                Gulfton     11.2  Meeting  Completed
24               Downtown     11.8  Meeting  Completed
25                Houston     21.9  Meeting  Completed
27                   Cary      8.0  Meeting  Completed
28                 Durham     10.4  Meeting  Completed
29                   Cary     10.4  Meeting  Completed
32    Lake Wellingborough      7.2  Meeting  Completed
33            Whitebridge      7.6  Meeting  Completed
34                Raleigh     17.1  Meeting  Completed
35                Umstead     15.1  Meeting  Completed
36                   Cary     40.2  Meeting  Completed
46                Raleigh     18.7  Meeting  Completed
49                   Cary     12.9  Meeting  Completed
50                Raleigh     19.0  Meeting  Completed
51       Leesville Hollow     14.7  Meeting  Completed
52                   Cary     15.7  Meeting  Completed
54                   Cary      5.2  Meeting  Completed
55                 Durham     10.4  Meeting  Completed
56                   Cary     10.1  Meeting  Completed
57                   Apex      5.8  Meeting  Completed
...                   ...      ...      ...        ...
1090     Unknown Location      5.3  Meeting  Completed
1091     Unknown Location     11.6  Meeting  Completed
1092     Unknown Location     23.2  Meeting  Completed
1094     Unknown Location     12.3  Meeting  Completed
1095               Lahore     14.0  Meeting  Completed
1099     Unknown Location      6.2  Meeting  Completed
1100     Unknown Location      9.6  Meeting  Completed
1102               Lahore      7.1  Meeting  Completed
1103     Unknown Location      6.3  Meeting  Completed
1104               Lahore     10.7  Meeting  Completed
1105               Lahore      5.3  Meeting  Completed
1115               Lahore      6.2  Meeting  Completed
1116               Lahore      7.7  Meeting  Completed
1118     Unknown Location      7.9  Meeting  Completed
1123              Kar?chi      7.9  Meeting  Completed
1124              Kar?chi      5.5  Meeting  Completed
1125     Unknown Location     10.3  Meeting  Completed
1126              Kar?chi     10.4  Meeting  Completed
1128     Unknown Location      8.5  Meeting  Completed
1131              Kar?chi      5.1  Meeting  Completed
1133     Unknown Location     11.6  Meeting  Completed
1134              Kar?chi     11.9  Meeting  Completed
1138              Kar?chi      6.1  Meeting  Completed
1142              Kar?chi      7.2  Meeting  Completed
1143     Unknown Location      6.4  Meeting  Completed
1144              Kar?chi     12.9  Meeting  Completed
1152     Unknown Location     16.2  Meeting  Completed
1153              Gampaha      6.4  Meeting  Completed
1154            Ilukwatta     48.2  Meeting  Completed
1155                  NaN  12204.7  Meeting  Completed

[654 rows x 8 columns]