In [1]:
import pandas as pd

In [6]:
df=pd.read_csv("/Users/exam/Desktop/uber.csv")

In [7]:
df

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
0,1/1/2016 21:11,1/1/2016 21:17,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain
1,1/2/2016 1:25,1/2/2016 1:37,Business,Fort Pierce,Fort Pierce,5.0,NaN
2,1/2/2016 20:25,1/2/2016 20:38,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies
3,1/5/2016 17:31,1/5/2016 17:45,Business,Fort Pierce,Fort Pierce,4.7,Meeting
4,1/6/2016 14:42,1/6/2016 15:49,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit
5,1/6/2016 17:15,1/6/2016 17:19,Business,West Palm Beach,West Palm Beach,4.3,Meal/Entertain
6,1/6/2016 17:30,1/6/2016 17:35,Business,West Palm Beach,Palm Beach,7.1,Meeting
7,1/7/2016 13:27,1/7/2016 13:33,Business,Cary,Cary,0.8,Meeting
8,1/10/2016 8:05,1/10/2016 8:25,Business,Cary,Morrisville,8.3,Meeting
9,1/10/2016 12:17,1/10/2016 12:44,Business,Jamaica,New York,16.5,Customer Visit
10,1/10/2016 15:08,1/10/2016 15:51,Business,New York,Queens,10.8,Meeting
11,1/10/2016 18:18,1/10/2016 18:53,Business,Elmhurst,New York,7.5,Meeting
12,1/10/2016 19:12,1/10/2016 19:32,Business,Midtown,East Harlem,6.2,Meeting
13,1/11/2016 8:55,1/11/2016 9:21,Business,East Harlem,NoMad,6.4,Temporary Site
14,1/11/2016 11:56,1/11/2016 12:03,Business,Flatiron District,Midtown,1.6,Errand/Supplies
15,1/11/2016 13:32,1/11/2016 13:46,Business,Midtown,Midtown East,1.7,Meal/Entertain
16,1/11/2016 14:30,1/11/2016 14:43,Business,Midtown East,Midtown,1.9,Meal/Entertain
17,1/12/2016 12:33,1/12/2016 12:49,Business,Midtown,Hudson Square,1.9,Meal/Entertain
18,1/12/2016 12:53,1/12/2016 13:09,Business,Hudson Square,Lower Manhattan,4.0,Meal/Entertain
19,1/12/2016 14:42,1/12/2016 14:56,Business,Lower Manhattan,Hudson Square,1.8,Errand/Supplies
20,1/12/2016 15:13,1/12/2016 15:28,Business,Hudson Square,Hell's Kitchen,2.4,Customer Visit
21,1/12/2016 15:42,1/12/2016 15:54,Business,Hell's Kitchen,Midtown,2.0,Errand/Supplies
22,1/12/2016 16:02,1/12/2016 17:00,Business,New York,Queens County,15.1,Meeting
23,1/13/2016 13:54,1/13/2016 14:07,Business,Downtown,Gulfton,11.2,Meeting
24,1/13/2016 15:00,1/13/2016 15:28,Business,Gulfton,Downtown,11.8,Meeting
25,1/14/2016 16:29,1/14/2016 17:05,Business,Houston,Houston,21.9,Customer Visit
26,1/14/2016 21:39,1/14/2016 21:45,Business,Eagan Park,Jamestown Court,3.9,Errand/Supplies
27,1/15/2016 0:41,1/15/2016 1:01,Business,Morrisville,Cary,8.0,Errand/Supplies
28,1/15/2016 11:43,1/15/2016 12:03,Business,Cary,Durham,10.4,Meal/Entertain
29,1/15/2016 13:26,1/15/2016 13:44,Business,Durham,Cary,10.4,Meal/Entertain
...,...,...,...,...,...,...,...
1126,12/28/2016 11:42,12/28/2016 12:12,Business,Unknown Location,Kar?chi,10.4,Errand/Supplies
1127,12/28/2016 13:53,12/28/2016 14:01,Business,Kar?chi,Kar?chi,2.0,Errand/Supplies
1128,12/28/2016 15:04,12/28/2016 15:39,Business,Kar?chi,Unknown Location,8.5,Meal/Entertain
1129,12/28/2016 17:02,12/28/2016 17:16,Business,Unknown Location,Kar?chi,4.4,Errand/Supplies
1130,12/28/2016 18:33,12/28/2016 18:56,Business,Kar?chi,Kar?chi,3.8,Errand/Supplies
1131,12/28/2016 22:44,12/28/2016 23:18,Business,Kar?chi,Kar?chi,5.1,Errand/Supplies
1132,12/29/2016 0:49,12/29/2016 1:06,Business,Kar?chi,Kar?chi,3.8,Errand/Supplies
1133,12/29/2016 9:44,12/29/2016 10:07,Business,Kar?chi,Unknown Location,11.6,Meal/Entertain
1134,12/29/2016 11:28,12/29/2016 12:00,Business,Unknown Location,Kar?chi,11.9,Meal/Entertain
1135,12/29/2016 12:25,12/29/2016 12:33,Business,Kar?chi,Kar?chi,1.4,Errand/Supplies
1136,12/29/2016 13:17,12/29/2016 13:24,Business,Kar?chi,Kar?chi,1.1,Errand/Supplies
1137,12/29/2016 13:56,12/29/2016 14:11,Business,Kar?chi,Kar?chi,4.1,Airport/Travel
1138,12/29/2016 14:42,12/29/2016 14:58,Business,Kar?chi,Kar?chi,6.1,Between Offices
1139,12/29/2016 15:05,12/29/2016 15:16,Business,Kar?chi,Kar?chi,1.3,Errand/Supplies
1140,12/29/2016 18:59,12/29/2016 19:14,Business,Kar?chi,Unknown Location,3.0,Meal/Entertain
1141,12/29/2016 19:50,12/29/2016 20:10,Business,Unknown Location,Kar?chi,4.1,Customer Visit
1142,12/29/2016 20:15,12/29/2016 20:45,Business,Kar?chi,Kar?chi,7.2,Meeting
1143,12/29/2016 20:53,12/29/2016 21:42,Business,Kar?chi,Unknown Location,6.4,NaN
1144,12/29/2016 23:14,12/29/2016 23:47,Business,Unknown Location,Kar?chi,12.9,Meeting
1145,12/30/2016 10:15,12/30/2016 10:33,Business,Kar?chi,Kar?chi,2.8,Errand/Supplies
1146,12/30/2016 11:31,12/30/2016 11:56,Business,Kar?chi,Kar?chi,2.9,Errand/Supplies
1147,12/30/2016 15:41,12/30/2016 16:03,Business,Kar?chi,Kar?chi,4.6,Errand/Supplies
1148,12/30/2016 16:45,12/30/2016 17:08,Business,Kar?chi,Kar?chi,4.6,Meeting
1149,12/30/2016 23:06,12/30/2016 23:10,Business,Kar?chi,Kar?chi,0.8,Customer Visit
1150,12/31/2016 1:07,12/31/2016 1:14,Business,Kar?chi,Kar?chi,0.7,Meeting
1151,12/31/2016 13:24,12/31/2016 13:42,Business,Kar?chi,Unknown Location,3.9,Temporary Site
1152,12/31/2016 15:03,12/31/2016 15:38,Business,Unknown Location,Unknown Location,16.2,Meeting
1153,12/31/2016 21:32,12/31/2016 21:50,Business,Katunayake,Gampaha,6.4,Temporary Site
1154,12/31/2016 22:08,12/31/2016 23:51,Business,Gampaha,Ilukwatta,48.2,Temporary Site
1155,Totals,NaN,NaN,NaN,NaN,12204.7,NaN

In [8]:
df.info

<bound method DataFrame.info of            START_DATE*         END_DATE* CATEGORY*             START*  \
0       1/1/2016 21:11    1/1/2016 21:17  Business        Fort Pierce
1        1/2/2016 1:25     1/2/2016 1:37  Business        Fort Pierce
2       1/2/2016 20:25    1/2/2016 20:38  Business        Fort Pierce
3       1/5/2016 17:31    1/5/2016 17:45  Business        Fort Pierce
4       1/6/2016 14:42    1/6/2016 15:49  Business        Fort Pierce
5       1/6/2016 17:15    1/6/2016 17:19  Business    West Palm Beach
6       1/6/2016 17:30    1/6/2016 17:35  Business    West Palm Beach
7       1/7/2016 13:27    1/7/2016 13:33  Business               Cary
8       1/10/2016 8:05    1/10/2016 8:25  Business               Cary
9      1/10/2016 12:17   1/10/2016 12:44  Business            Jamaica
10     1/10/2016 15:08   1/10/2016 15:51  Business           New York
11     1/10/2016 18:18   1/10/2016 18:53  Business           Elmhurst
12     1/10/2016 19:12   1/10/2016 19:32  Business            Midtown
13      1/11/2016 8:55    1/11/2016 9:21  Business        East Harlem
14     1/11/2016 11:56   1/11/2016 12:03  Business  Flatiron District
15     1/11/2016 13:32   1/11/2016 13:46  Business            Midtown
16     1/11/2016 14:30   1/11/2016 14:43  Business       Midtown East
17     1/12/2016 12:33   1/12/2016 12:49  Business            Midtown
18     1/12/2016 12:53   1/12/2016 13:09  Business      Hudson Square
19     1/12/2016 14:42   1/12/2016 14:56  Business    Lower Manhattan
20     1/12/2016 15:13   1/12/2016 15:28  Business      Hudson Square
21     1/12/2016 15:42   1/12/2016 15:54  Business     Hell's Kitchen
22     1/12/2016 16:02   1/12/2016 17:00  Business           New York
23     1/13/2016 13:54   1/13/2016 14:07  Business           Downtown
24     1/13/2016 15:00   1/13/2016 15:28  Business            Gulfton
25     1/14/2016 16:29   1/14/2016 17:05  Business            Houston
26     1/14/2016 21:39   1/14/2016 21:45  Business         Eagan Park
27      1/15/2016 0:41    1/15/2016 1:01  Business        Morrisville
28     1/15/2016 11:43   1/15/2016 12:03  Business               Cary
29     1/15/2016 13:26   1/15/2016 13:44  Business             Durham
...                ...               ...       ...                ...
1126  12/28/2016 11:42  12/28/2016 12:12  Business   Unknown Location
1127  12/28/2016 13:53  12/28/2016 14:01  Business            Kar?chi
1128  12/28/2016 15:04  12/28/2016 15:39  Business            Kar?chi
1129  12/28/2016 17:02  12/28/2016 17:16  Business   Unknown Location
1130  12/28/2016 18:33  12/28/2016 18:56  Business            Kar?chi
1131  12/28/2016 22:44  12/28/2016 23:18  Business            Kar?chi
1132   12/29/2016 0:49   12/29/2016 1:06  Business            Kar?chi
1133   12/29/2016 9:44  12/29/2016 10:07  Business            Kar?chi
1134  12/29/2016 11:28  12/29/2016 12:00  Business   Unknown Location
1135  12/29/2016 12:25  12/29/2016 12:33  Business            Kar?chi
1136  12/29/2016 13:17  12/29/2016 13:24  Business            Kar?chi
1137  12/29/2016 13:56  12/29/2016 14:11  Business            Kar?chi
1138  12/29/2016 14:42  12/29/2016 14:58  Business            Kar?chi
1139  12/29/2016 15:05  12/29/2016 15:16  Business            Kar?chi
1140  12/29/2016 18:59  12/29/2016 19:14  Business            Kar?chi
1141  12/29/2016 19:50  12/29/2016 20:10  Business   Unknown Location
1142  12/29/2016 20:15  12/29/2016 20:45  Business            Kar?chi
1143  12/29/2016 20:53  12/29/2016 21:42  Business            Kar?chi
1144  12/29/2016 23:14  12/29/2016 23:47  Business   Unknown Location
1145  12/30/2016 10:15  12/30/2016 10:33  Business            Kar?chi
1146  12/30/2016 11:31  12/30/2016 11:56  Business            Kar?chi
1147  12/30/2016 15:41  12/30/2016 16:03  Business            Kar?chi
1148  12/30/2016 16:45  12/30/2016 17:08  Business            Kar?chi
1149  12/30/2016 23:06  12/30/2016 23:10  Business            Kar?chi
1150   12/31/2016 1:07   12/31/2016 1:14  Business            Kar?chi
1151  12/31/2016 13:24  12/31/2016 13:42  Business            Kar?chi
1152  12/31/2016 15:03  12/31/2016 15:38  Business   Unknown Location
1153  12/31/2016 21:32  12/31/2016 21:50  Business         Katunayake
1154  12/31/2016 22:08  12/31/2016 23:51  Business            Gampaha
1155            Totals               NaN       NaN                NaN

                 STOP*   MILES*         PURPOSE*
0          Fort Pierce      5.1   Meal/Entertain
1          Fort Pierce      5.0              NaN
2          Fort Pierce      4.8  Errand/Supplies
3          Fort Pierce      4.7          Meeting
4      West Palm Beach     63.7   Customer Visit
5      West Palm Beach      4.3   Meal/Entertain
6           Palm Beach      7.1          Meeting
7                 Cary      0.8          Meeting
8          Morrisville      8.3          Meeting
9             New York     16.5   Customer Visit
10              Queens     10.8          Meeting
11            New York      7.5          Meeting
12         East Harlem      6.2          Meeting
13               NoMad      6.4   Temporary Site
14             Midtown      1.6  Errand/Supplies
15        Midtown East      1.7   Meal/Entertain
16             Midtown      1.9   Meal/Entertain
17       Hudson Square      1.9   Meal/Entertain
18     Lower Manhattan      4.0   Meal/Entertain
19       Hudson Square      1.8  Errand/Supplies
20      Hell's Kitchen      2.4   Customer Visit
21             Midtown      2.0  Errand/Supplies
22       Queens County     15.1          Meeting
23             Gulfton     11.2          Meeting
24            Downtown     11.8          Meeting
25             Houston     21.9   Customer Visit
26     Jamestown Court      3.9  Errand/Supplies
27                Cary      8.0  Errand/Supplies
28              Durham     10.4   Meal/Entertain
29                Cary     10.4   Meal/Entertain
...                ...      ...              ...
1126           Kar?chi     10.4  Errand/Supplies
1127           Kar?chi      2.0  Errand/Supplies
1128  Unknown Location      8.5   Meal/Entertain
1129           Kar?chi      4.4  Errand/Supplies
1130           Kar?chi      3.8  Errand/Supplies
1131           Kar?chi      5.1  Errand/Supplies
1132           Kar?chi      3.8  Errand/Supplies
1133  Unknown Location     11.6   Meal/Entertain
1134           Kar?chi     11.9   Meal/Entertain
1135           Kar?chi      1.4  Errand/Supplies
1136           Kar?chi      1.1  Errand/Supplies
1137           Kar?chi      4.1   Airport/Travel
1138           Kar?chi      6.1  Between Offices
1139           Kar?chi      1.3  Errand/Supplies
1140  Unknown Location      3.0   Meal/Entertain
1141           Kar?chi      4.1   Customer Visit
1142           Kar?chi      7.2          Meeting
1143  Unknown Location      6.4              NaN
1144           Kar?chi     12.9          Meeting
1145           Kar?chi      2.8  Errand/Supplies
1146           Kar?chi      2.9  Errand/Supplies
1147           Kar?chi      4.6  Errand/Supplies
1148           Kar?chi      4.6          Meeting
1149           Kar?chi      0.8   Customer Visit
1150           Kar?chi      0.7          Meeting
1151  Unknown Location      3.9   Temporary Site
1152  Unknown Location     16.2          Meeting
1153           Gampaha      6.4   Temporary Site
1154         Ilukwatta     48.2   Temporary Site
1155               NaN  12204.7              NaN

[1156 rows x 7 columns]>

In [9]:
df.count

<bound method DataFrame.count of            START_DATE*         END_DATE* CATEGORY*             START*  \
0       1/1/2016 21:11    1/1/2016 21:17  Business        Fort Pierce
1        1/2/2016 1:25     1/2/2016 1:37  Business        Fort Pierce
2       1/2/2016 20:25    1/2/2016 20:38  Business        Fort Pierce
3       1/5/2016 17:31    1/5/2016 17:45  Business        Fort Pierce
4       1/6/2016 14:42    1/6/2016 15:49  Business        Fort Pierce
5       1/6/2016 17:15    1/6/2016 17:19  Business    West Palm Beach
6       1/6/2016 17:30    1/6/2016 17:35  Business    West Palm Beach
7       1/7/2016 13:27    1/7/2016 13:33  Business               Cary
8       1/10/2016 8:05    1/10/2016 8:25  Business               Cary
9      1/10/2016 12:17   1/10/2016 12:44  Business            Jamaica
10     1/10/2016 15:08   1/10/2016 15:51  Business           New York
11     1/10/2016 18:18   1/10/2016 18:53  Business           Elmhurst
12     1/10/2016 19:12   1/10/2016 19:32  Business            Midtown
13      1/11/2016 8:55    1/11/2016 9:21  Business        East Harlem
14     1/11/2016 11:56   1/11/2016 12:03  Business  Flatiron District
15     1/11/2016 13:32   1/11/2016 13:46  Business            Midtown
16     1/11/2016 14:30   1/11/2016 14:43  Business       Midtown East
17     1/12/2016 12:33   1/12/2016 12:49  Business            Midtown
18     1/12/2016 12:53   1/12/2016 13:09  Business      Hudson Square
19     1/12/2016 14:42   1/12/2016 14:56  Business    Lower Manhattan
20     1/12/2016 15:13   1/12/2016 15:28  Business      Hudson Square
21     1/12/2016 15:42   1/12/2016 15:54  Business     Hell's Kitchen
22     1/12/2016 16:02   1/12/2016 17:00  Business           New York
23     1/13/2016 13:54   1/13/2016 14:07  Business           Downtown
24     1/13/2016 15:00   1/13/2016 15:28  Business            Gulfton
25     1/14/2016 16:29   1/14/2016 17:05  Business            Houston
26     1/14/2016 21:39   1/14/2016 21:45  Business         Eagan Park
27      1/15/2016 0:41    1/15/2016 1:01  Business        Morrisville
28     1/15/2016 11:43   1/15/2016 12:03  Business               Cary
29     1/15/2016 13:26   1/15/2016 13:44  Business             Durham
...                ...               ...       ...                ...
1126  12/28/2016 11:42  12/28/2016 12:12  Business   Unknown Location
1127  12/28/2016 13:53  12/28/2016 14:01  Business            Kar?chi
1128  12/28/2016 15:04  12/28/2016 15:39  Business            Kar?chi
1129  12/28/2016 17:02  12/28/2016 17:16  Business   Unknown Location
1130  12/28/2016 18:33  12/28/2016 18:56  Business            Kar?chi
1131  12/28/2016 22:44  12/28/2016 23:18  Business            Kar?chi
1132   12/29/2016 0:49   12/29/2016 1:06  Business            Kar?chi
1133   12/29/2016 9:44  12/29/2016 10:07  Business            Kar?chi
1134  12/29/2016 11:28  12/29/2016 12:00  Business   Unknown Location
1135  12/29/2016 12:25  12/29/2016 12:33  Business            Kar?chi
1136  12/29/2016 13:17  12/29/2016 13:24  Business            Kar?chi
1137  12/29/2016 13:56  12/29/2016 14:11  Business            Kar?chi
1138  12/29/2016 14:42  12/29/2016 14:58  Business            Kar?chi
1139  12/29/2016 15:05  12/29/2016 15:16  Business            Kar?chi
1140  12/29/2016 18:59  12/29/2016 19:14  Business            Kar?chi
1141  12/29/2016 19:50  12/29/2016 20:10  Business   Unknown Location
1142  12/29/2016 20:15  12/29/2016 20:45  Business            Kar?chi
1143  12/29/2016 20:53  12/29/2016 21:42  Business            Kar?chi
1144  12/29/2016 23:14  12/29/2016 23:47  Business   Unknown Location
1145  12/30/2016 10:15  12/30/2016 10:33  Business            Kar?chi
1146  12/30/2016 11:31  12/30/2016 11:56  Business            Kar?chi
1147  12/30/2016 15:41  12/30/2016 16:03  Business            Kar?chi
1148  12/30/2016 16:45  12/30/2016 17:08  Business            Kar?chi
1149  12/30/2016 23:06  12/30/2016 23:10  Business            Kar?chi
1150   12/31/2016 1:07   12/31/2016 1:14  Business            Kar?chi
1151  12/31/2016 13:24  12/31/2016 13:42  Business            Kar?chi
1152  12/31/2016 15:03  12/31/2016 15:38  Business   Unknown Location
1153  12/31/2016 21:32  12/31/2016 21:50  Business         Katunayake
1154  12/31/2016 22:08  12/31/2016 23:51  Business            Gampaha
1155            Totals               NaN       NaN                NaN

                 STOP*   MILES*         PURPOSE*
0          Fort Pierce      5.1   Meal/Entertain
1          Fort Pierce      5.0              NaN
2          Fort Pierce      4.8  Errand/Supplies
3          Fort Pierce      4.7          Meeting
4      West Palm Beach     63.7   Customer Visit
5      West Palm Beach      4.3   Meal/Entertain
6           Palm Beach      7.1          Meeting
7                 Cary      0.8          Meeting
8          Morrisville      8.3          Meeting
9             New York     16.5   Customer Visit
10              Queens     10.8          Meeting
11            New York      7.5          Meeting
12         East Harlem      6.2          Meeting
13               NoMad      6.4   Temporary Site
14             Midtown      1.6  Errand/Supplies
15        Midtown East      1.7   Meal/Entertain
16             Midtown      1.9   Meal/Entertain
17       Hudson Square      1.9   Meal/Entertain
18     Lower Manhattan      4.0   Meal/Entertain
19       Hudson Square      1.8  Errand/Supplies
20      Hell's Kitchen      2.4   Customer Visit
21             Midtown      2.0  Errand/Supplies
22       Queens County     15.1          Meeting
23             Gulfton     11.2          Meeting
24            Downtown     11.8          Meeting
25             Houston     21.9   Customer Visit
26     Jamestown Court      3.9  Errand/Supplies
27                Cary      8.0  Errand/Supplies
28              Durham     10.4   Meal/Entertain
29                Cary     10.4   Meal/Entertain
...                ...      ...              ...
1126           Kar?chi     10.4  Errand/Supplies
1127           Kar?chi      2.0  Errand/Supplies
1128  Unknown Location      8.5   Meal/Entertain
1129           Kar?chi      4.4  Errand/Supplies
1130           Kar?chi      3.8  Errand/Supplies
1131           Kar?chi      5.1  Errand/Supplies
1132           Kar?chi      3.8  Errand/Supplies
1133  Unknown Location     11.6   Meal/Entertain
1134           Kar?chi     11.9   Meal/Entertain
1135           Kar?chi      1.4  Errand/Supplies
1136           Kar?chi      1.1  Errand/Supplies
1137           Kar?chi      4.1   Airport/Travel
1138           Kar?chi      6.1  Between Offices
1139           Kar?chi      1.3  Errand/Supplies
1140  Unknown Location      3.0   Meal/Entertain
1141           Kar?chi      4.1   Customer Visit
1142           Kar?chi      7.2          Meeting
1143  Unknown Location      6.4              NaN
1144           Kar?chi     12.9          Meeting
1145           Kar?chi      2.8  Errand/Supplies
1146           Kar?chi      2.9  Errand/Supplies
1147           Kar?chi      4.6  Errand/Supplies
1148           Kar?chi      4.6          Meeting
1149           Kar?chi      0.8   Customer Visit
1150           Kar?chi      0.7          Meeting
1151  Unknown Location      3.9   Temporary Site
1152  Unknown Location     16.2          Meeting
1153           Gampaha      6.4   Temporary Site
1154         Ilukwatta     48.2   Temporary Site
1155               NaN  12204.7              NaN

[1156 rows x 7 columns]>

In [10]:
df.index

RangeIndex(start=0, stop=1156, step=1)

In [11]:
df.columns

Index(['START_DATE*', 'END_DATE*', 'CATEGORY*', 'START*', 'STOP*', 'MILES*',
       'PURPOSE*'],
      dtype='object')

In [12]:
df.count

<bound method DataFrame.count of            START_DATE*         END_DATE* CATEGORY*             START*  \
0       1/1/2016 21:11    1/1/2016 21:17  Business        Fort Pierce
1        1/2/2016 1:25     1/2/2016 1:37  Business        Fort Pierce
2       1/2/2016 20:25    1/2/2016 20:38  Business        Fort Pierce
3       1/5/2016 17:31    1/5/2016 17:45  Business        Fort Pierce
4       1/6/2016 14:42    1/6/2016 15:49  Business        Fort Pierce
5       1/6/2016 17:15    1/6/2016 17:19  Business    West Palm Beach
6       1/6/2016 17:30    1/6/2016 17:35  Business    West Palm Beach
7       1/7/2016 13:27    1/7/2016 13:33  Business               Cary
8       1/10/2016 8:05    1/10/2016 8:25  Business               Cary
9      1/10/2016 12:17   1/10/2016 12:44  Business            Jamaica
10     1/10/2016 15:08   1/10/2016 15:51  Business           New York
11     1/10/2016 18:18   1/10/2016 18:53  Business           Elmhurst
12     1/10/2016 19:12   1/10/2016 19:32  Business            Midtown
13      1/11/2016 8:55    1/11/2016 9:21  Business        East Harlem
14     1/11/2016 11:56   1/11/2016 12:03  Business  Flatiron District
15     1/11/2016 13:32   1/11/2016 13:46  Business            Midtown
16     1/11/2016 14:30   1/11/2016 14:43  Business       Midtown East
17     1/12/2016 12:33   1/12/2016 12:49  Business            Midtown
18     1/12/2016 12:53   1/12/2016 13:09  Business      Hudson Square
19     1/12/2016 14:42   1/12/2016 14:56  Business    Lower Manhattan
20     1/12/2016 15:13   1/12/2016 15:28  Business      Hudson Square
21     1/12/2016 15:42   1/12/2016 15:54  Business     Hell's Kitchen
22     1/12/2016 16:02   1/12/2016 17:00  Business           New York
23     1/13/2016 13:54   1/13/2016 14:07  Business           Downtown
24     1/13/2016 15:00   1/13/2016 15:28  Business            Gulfton
25     1/14/2016 16:29   1/14/2016 17:05  Business            Houston
26     1/14/2016 21:39   1/14/2016 21:45  Business         Eagan Park
27      1/15/2016 0:41    1/15/2016 1:01  Business        Morrisville
28     1/15/2016 11:43   1/15/2016 12:03  Business               Cary
29     1/15/2016 13:26   1/15/2016 13:44  Business             Durham
...                ...               ...       ...                ...
1126  12/28/2016 11:42  12/28/2016 12:12  Business   Unknown Location
1127  12/28/2016 13:53  12/28/2016 14:01  Business            Kar?chi
1128  12/28/2016 15:04  12/28/2016 15:39  Business            Kar?chi
1129  12/28/2016 17:02  12/28/2016 17:16  Business   Unknown Location
1130  12/28/2016 18:33  12/28/2016 18:56  Business            Kar?chi
1131  12/28/2016 22:44  12/28/2016 23:18  Business            Kar?chi
1132   12/29/2016 0:49   12/29/2016 1:06  Business            Kar?chi
1133   12/29/2016 9:44  12/29/2016 10:07  Business            Kar?chi
1134  12/29/2016 11:28  12/29/2016 12:00  Business   Unknown Location
1135  12/29/2016 12:25  12/29/2016 12:33  Business            Kar?chi
1136  12/29/2016 13:17  12/29/2016 13:24  Business            Kar?chi
1137  12/29/2016 13:56  12/29/2016 14:11  Business            Kar?chi
1138  12/29/2016 14:42  12/29/2016 14:58  Business            Kar?chi
1139  12/29/2016 15:05  12/29/2016 15:16  Business            Kar?chi
1140  12/29/2016 18:59  12/29/2016 19:14  Business            Kar?chi
1141  12/29/2016 19:50  12/29/2016 20:10  Business   Unknown Location
1142  12/29/2016 20:15  12/29/2016 20:45  Business            Kar?chi
1143  12/29/2016 20:53  12/29/2016 21:42  Business            Kar?chi
1144  12/29/2016 23:14  12/29/2016 23:47  Business   Unknown Location
1145  12/30/2016 10:15  12/30/2016 10:33  Business            Kar?chi
1146  12/30/2016 11:31  12/30/2016 11:56  Business            Kar?chi
1147  12/30/2016 15:41  12/30/2016 16:03  Business            Kar?chi
1148  12/30/2016 16:45  12/30/2016 17:08  Business            Kar?chi
1149  12/30/2016 23:06  12/30/2016 23:10  Business            Kar?chi
1150   12/31/2016 1:07   12/31/2016 1:14  Business            Kar?chi
1151  12/31/2016 13:24  12/31/2016 13:42  Business            Kar?chi
1152  12/31/2016 15:03  12/31/2016 15:38  Business   Unknown Location
1153  12/31/2016 21:32  12/31/2016 21:50  Business         Katunayake
1154  12/31/2016 22:08  12/31/2016 23:51  Business            Gampaha
1155            Totals               NaN       NaN                NaN

                 STOP*   MILES*         PURPOSE*
0          Fort Pierce      5.1   Meal/Entertain
1          Fort Pierce      5.0              NaN
2          Fort Pierce      4.8  Errand/Supplies
3          Fort Pierce      4.7          Meeting
4      West Palm Beach     63.7   Customer Visit
5      West Palm Beach      4.3   Meal/Entertain
6           Palm Beach      7.1          Meeting
7                 Cary      0.8          Meeting
8          Morrisville      8.3          Meeting
9             New York     16.5   Customer Visit
10              Queens     10.8          Meeting
11            New York      7.5          Meeting
12         East Harlem      6.2          Meeting
13               NoMad      6.4   Temporary Site
14             Midtown      1.6  Errand/Supplies
15        Midtown East      1.7   Meal/Entertain
16             Midtown      1.9   Meal/Entertain
17       Hudson Square      1.9   Meal/Entertain
18     Lower Manhattan      4.0   Meal/Entertain
19       Hudson Square      1.8  Errand/Supplies
20      Hell's Kitchen      2.4   Customer Visit
21             Midtown      2.0  Errand/Supplies
22       Queens County     15.1          Meeting
23             Gulfton     11.2          Meeting
24            Downtown     11.8          Meeting
25             Houston     21.9   Customer Visit
26     Jamestown Court      3.9  Errand/Supplies
27                Cary      8.0  Errand/Supplies
28              Durham     10.4   Meal/Entertain
29                Cary     10.4   Meal/Entertain
...                ...      ...              ...
1126           Kar?chi     10.4  Errand/Supplies
1127           Kar?chi      2.0  Errand/Supplies
1128  Unknown Location      8.5   Meal/Entertain
1129           Kar?chi      4.4  Errand/Supplies
1130           Kar?chi      3.8  Errand/Supplies
1131           Kar?chi      5.1  Errand/Supplies
1132           Kar?chi      3.8  Errand/Supplies
1133  Unknown Location     11.6   Meal/Entertain
1134           Kar?chi     11.9   Meal/Entertain
1135           Kar?chi      1.4  Errand/Supplies
1136           Kar?chi      1.1  Errand/Supplies
1137           Kar?chi      4.1   Airport/Travel
1138           Kar?chi      6.1  Between Offices
1139           Kar?chi      1.3  Errand/Supplies
1140  Unknown Location      3.0   Meal/Entertain
1141           Kar?chi      4.1   Customer Visit
1142           Kar?chi      7.2          Meeting
1143  Unknown Location      6.4              NaN
1144           Kar?chi     12.9          Meeting
1145           Kar?chi      2.8  Errand/Supplies
1146           Kar?chi      2.9  Errand/Supplies
1147           Kar?chi      4.6  Errand/Supplies
1148           Kar?chi      4.6          Meeting
1149           Kar?chi      0.8   Customer Visit
1150           Kar?chi      0.7          Meeting
1151  Unknown Location      3.9   Temporary Site
1152  Unknown Location     16.2          Meeting
1153           Gampaha      6.4   Temporary Site
1154         Ilukwatta     48.2   Temporary Site
1155               NaN  12204.7              NaN

[1156 rows x 7 columns]>

In [13]:
df.head()

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
0,1/1/2016 21:11,1/1/2016 21:17,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain
1,1/2/2016 1:25,1/2/2016 1:37,Business,Fort Pierce,Fort Pierce,5.0,NaN
2,1/2/2016 20:25,1/2/2016 20:38,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies
3,1/5/2016 17:31,1/5/2016 17:45,Business,Fort Pierce,Fort Pierce,4.7,Meeting
4,1/6/2016 14:42,1/6/2016 15:49,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit

In [14]:
df.tail()

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
1151,12/31/2016 13:24,12/31/2016 13:42,Business,Kar?chi,Unknown Location,3.9,Temporary Site
1152,12/31/2016 15:03,12/31/2016 15:38,Business,Unknown Location,Unknown Location,16.2,Meeting
1153,12/31/2016 21:32,12/31/2016 21:50,Business,Katunayake,Gampaha,6.4,Temporary Site
1154,12/31/2016 22:08,12/31/2016 23:51,Business,Gampaha,Ilukwatta,48.2,Temporary Site
1155,Totals,NaN,NaN,NaN,NaN,12204.7,NaN

In [15]:
df.head(10)

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
0,1/1/2016 21:11,1/1/2016 21:17,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain
1,1/2/2016 1:25,1/2/2016 1:37,Business,Fort Pierce,Fort Pierce,5.0,NaN
2,1/2/2016 20:25,1/2/2016 20:38,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies
3,1/5/2016 17:31,1/5/2016 17:45,Business,Fort Pierce,Fort Pierce,4.7,Meeting
4,1/6/2016 14:42,1/6/2016 15:49,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit
5,1/6/2016 17:15,1/6/2016 17:19,Business,West Palm Beach,West Palm Beach,4.3,Meal/Entertain
6,1/6/2016 17:30,1/6/2016 17:35,Business,West Palm Beach,Palm Beach,7.1,Meeting
7,1/7/2016 13:27,1/7/2016 13:33,Business,Cary,Cary,0.8,Meeting
8,1/10/2016 8:05,1/10/2016 8:25,Business,Cary,Morrisville,8.3,Meeting
9,1/10/2016 12:17,1/10/2016 12:44,Business,Jamaica,New York,16.5,Customer Visit

In [16]:
df[3:]

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
3,1/5/2016 17:31,1/5/2016 17:45,Business,Fort Pierce,Fort Pierce,4.7,Meeting
4,1/6/2016 14:42,1/6/2016 15:49,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit
5,1/6/2016 17:15,1/6/2016 17:19,Business,West Palm Beach,West Palm Beach,4.3,Meal/Entertain
6,1/6/2016 17:30,1/6/2016 17:35,Business,West Palm Beach,Palm Beach,7.1,Meeting
7,1/7/2016 13:27,1/7/2016 13:33,Business,Cary,Cary,0.8,Meeting
8,1/10/2016 8:05,1/10/2016 8:25,Business,Cary,Morrisville,8.3,Meeting
9,1/10/2016 12:17,1/10/2016 12:44,Business,Jamaica,New York,16.5,Customer Visit
10,1/10/2016 15:08,1/10/2016 15:51,Business,New York,Queens,10.8,Meeting
11,1/10/2016 18:18,1/10/2016 18:53,Business,Elmhurst,New York,7.5,Meeting
12,1/10/2016 19:12,1/10/2016 19:32,Business,Midtown,East Harlem,6.2,Meeting
13,1/11/2016 8:55,1/11/2016 9:21,Business,East Harlem,NoMad,6.4,Temporary Site
14,1/11/2016 11:56,1/11/2016 12:03,Business,Flatiron District,Midtown,1.6,Errand/Supplies
15,1/11/2016 13:32,1/11/2016 13:46,Business,Midtown,Midtown East,1.7,Meal/Entertain
16,1/11/2016 14:30,1/11/2016 14:43,Business,Midtown East,Midtown,1.9,Meal/Entertain
17,1/12/2016 12:33,1/12/2016 12:49,Business,Midtown,Hudson Square,1.9,Meal/Entertain
18,1/12/2016 12:53,1/12/2016 13:09,Business,Hudson Square,Lower Manhattan,4.0,Meal/Entertain
19,1/12/2016 14:42,1/12/2016 14:56,Business,Lower Manhattan,Hudson Square,1.8,Errand/Supplies
20,1/12/2016 15:13,1/12/2016 15:28,Business,Hudson Square,Hell's Kitchen,2.4,Customer Visit
21,1/12/2016 15:42,1/12/2016 15:54,Business,Hell's Kitchen,Midtown,2.0,Errand/Supplies
22,1/12/2016 16:02,1/12/2016 17:00,Business,New York,Queens County,15.1,Meeting
23,1/13/2016 13:54,1/13/2016 14:07,Business,Downtown,Gulfton,11.2,Meeting
24,1/13/2016 15:00,1/13/2016 15:28,Business,Gulfton,Downtown,11.8,Meeting
25,1/14/2016 16:29,1/14/2016 17:05,Business,Houston,Houston,21.9,Customer Visit
26,1/14/2016 21:39,1/14/2016 21:45,Business,Eagan Park,Jamestown Court,3.9,Errand/Supplies
27,1/15/2016 0:41,1/15/2016 1:01,Business,Morrisville,Cary,8.0,Errand/Supplies
28,1/15/2016 11:43,1/15/2016 12:03,Business,Cary,Durham,10.4,Meal/Entertain
29,1/15/2016 13:26,1/15/2016 13:44,Business,Durham,Cary,10.4,Meal/Entertain
30,1/18/2016 14:55,1/18/2016 15:06,Business,Cary,Cary,4.8,Meal/Entertain
31,1/18/2016 16:13,1/18/2016 16:24,Business,Farmington Woods,Whitebridge,4.7,Meal/Entertain
32,1/19/2016 9:09,1/19/2016 9:23,Business,Whitebridge,Lake Wellingborough,7.2,NaN
...,...,...,...,...,...,...,...
1126,12/28/2016 11:42,12/28/2016 12:12,Business,Unknown Location,Kar?chi,10.4,Errand/Supplies
1127,12/28/2016 13:53,12/28/2016 14:01,Business,Kar?chi,Kar?chi,2.0,Errand/Supplies
1128,12/28/2016 15:04,12/28/2016 15:39,Business,Kar?chi,Unknown Location,8.5,Meal/Entertain
1129,12/28/2016 17:02,12/28/2016 17:16,Business,Unknown Location,Kar?chi,4.4,Errand/Supplies
1130,12/28/2016 18:33,12/28/2016 18:56,Business,Kar?chi,Kar?chi,3.8,Errand/Supplies
1131,12/28/2016 22:44,12/28/2016 23:18,Business,Kar?chi,Kar?chi,5.1,Errand/Supplies
1132,12/29/2016 0:49,12/29/2016 1:06,Business,Kar?chi,Kar?chi,3.8,Errand/Supplies
1133,12/29/2016 9:44,12/29/2016 10:07,Business,Kar?chi,Unknown Location,11.6,Meal/Entertain
1134,12/29/2016 11:28,12/29/2016 12:00,Business,Unknown Location,Kar?chi,11.9,Meal/Entertain
1135,12/29/2016 12:25,12/29/2016 12:33,Business,Kar?chi,Kar?chi,1.4,Errand/Supplies
1136,12/29/2016 13:17,12/29/2016 13:24,Business,Kar?chi,Kar?chi,1.1,Errand/Supplies
1137,12/29/2016 13:56,12/29/2016 14:11,Business,Kar?chi,Kar?chi,4.1,Airport/Travel
1138,12/29/2016 14:42,12/29/2016 14:58,Business,Kar?chi,Kar?chi,6.1,Between Offices
1139,12/29/2016 15:05,12/29/2016 15:16,Business,Kar?chi,Kar?chi,1.3,Errand/Supplies
1140,12/29/2016 18:59,12/29/2016 19:14,Business,Kar?chi,Unknown Location,3.0,Meal/Entertain
1141,12/29/2016 19:50,12/29/2016 20:10,Business,Unknown Location,Kar?chi,4.1,Customer Visit
1142,12/29/2016 20:15,12/29/2016 20:45,Business,Kar?chi,Kar?chi,7.2,Meeting
1143,12/29/2016 20:53,12/29/2016 21:42,Business,Kar?chi,Unknown Location,6.4,NaN
1144,12/29/2016 23:14,12/29/2016 23:47,Business,Unknown Location,Kar?chi,12.9,Meeting
1145,12/30/2016 10:15,12/30/2016 10:33,Business,Kar?chi,Kar?chi,2.8,Errand/Supplies
1146,12/30/2016 11:31,12/30/2016 11:56,Business,Kar?chi,Kar?chi,2.9,Errand/Supplies
1147,12/30/2016 15:41,12/30/2016 16:03,Business,Kar?chi,Kar?chi,4.6,Errand/Supplies
1148,12/30/2016 16:45,12/30/2016 17:08,Business,Kar?chi,Kar?chi,4.6,Meeting
1149,12/30/2016 23:06,12/30/2016 23:10,Business,Kar?chi,Kar?chi,0.8,Customer Visit
1150,12/31/2016 1:07,12/31/2016 1:14,Business,Kar?chi,Kar?chi,0.7,Meeting
1151,12/31/2016 13:24,12/31/2016 13:42,Business,Kar?chi,Unknown Location,3.9,Temporary Site
1152,12/31/2016 15:03,12/31/2016 15:38,Business,Unknown Location,Unknown Location,16.2,Meeting
1153,12/31/2016 21:32,12/31/2016 21:50,Business,Katunayake,Gampaha,6.4,Temporary Site
1154,12/31/2016 22:08,12/31/2016 23:51,Business,Gampaha,Ilukwatta,48.2,Temporary Site
1155,Totals,NaN,NaN,NaN,NaN,12204.7,NaN

In [17]:
import pandas as pd

In [18]:
db=pd.read_csv("/Users/exam/Desktop/netflix_titles.csv")

In [19]:
db

,s1,TV Show,3%,Unnamed: 3,"João Miguel, Bianca Comparato, Michel Gomes, Rodolfo Valente, Vaneza Oliveira, Rafael Lozano, Viviane Porto, Mel Fronckowiak, Sergio Mamberti, Zezé Motta, Celso Frateschi",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi & Fantasy","In a future where the elite inhabit an island paradise far from the crowded slums, you get one chance to join the 3% saved from squalor."
0,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
1,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
2,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
3,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...
4,s6,TV Show,46,Serdar Akar,"Erdal Beşikçioğlu, Yasemin Allen, Melis Birkan...",Turkey,"July 1, 2017",2016,TV-MA,1 Season,"International TV Shows, TV Dramas, TV Mysteries",A genetics professor experiments with a treatm...
5,s7,Movie,122,Yasir Al Yasiri,"Amina Khalil, Ahmed Dawood, Tarek Lotfy, Ahmed...",Egypt,"June 1, 2020",2019,TV-MA,95 min,"Horror Movies, International Movies","After an awful accident, a couple admitted to ..."
6,s8,Movie,187,Kevin Reynolds,"Samuel L. Jackson, John Heard, Kelly Rowan, Cl...",United States,"November 1, 2019",1997,R,119 min,Dramas,After one of his high school students attacks ...
7,s9,Movie,706,Shravan Kumar,"Divya Dutta, Atul Kulkarni, Mohan Agashe, Anup...",India,"April 1, 2019",2019,TV-14,118 min,"Horror Movies, International Movies","When a doctor goes missing, his psychiatrist w..."
8,s10,Movie,1920,Vikram Bhatt,"Rajneesh Duggal, Adah Sharma, Indraneil Sengup...",India,"December 15, 2017",2008,TV-MA,143 min,"Horror Movies, International Movies, Thrillers",An architect and his wife move into a castle t...
9,s11,Movie,1922,Zak Hilditch,"Thomas Jane, Molly Parker, Dylan Schmid, Kaitl...",United States,"October 20, 2017",2017,TV-MA,103 min,"Dramas, Thrillers",A farmer pens a confession admitting to his wi...
10,s12,TV Show,1983,NaN,"Robert Więckiewicz, Maciej Musiał, Michalina O...","Poland, United States","November 30, 2018",2018,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas","In this dark alt-history thriller, a naïve law..."
11,s13,TV Show,1994,Diego Enrique Osorno,NaN,Mexico,"May 17, 2019",2019,TV-MA,1 Season,"Crime TV Shows, Docuseries, International TV S...",Archival video and new interviews examine Mexi...
12,s14,Movie,2215,Nottapon Boonprakob,Artiwara Kongmalai,Thailand,"March 1, 2019",2018,TV-MA,89 min,"Documentaries, International Movies, Sports Mo...",This intimate documentary follows rock star Ar...
13,s15,Movie,3022,John Suits,"Omar Epps, Kate Walsh, Miranda Cosgrove, Angus...",United States,"March 19, 2020",2019,R,91 min,"Independent Movies, Sci-Fi & Fantasy, Thrillers",Stranded when the Earth is suddenly destroyed ...
14,s16,Movie,Oct-01,Kunle Afolayan,"Sadiq Daba, David Bailie, Kayode Olaiya, Kehin...",Nigeria,"September 1, 2019",2014,TV-14,149 min,"Dramas, International Movies, Thrillers",Against the backdrop of Nigeria's looming inde...
15,s17,TV Show,Feb-09,NaN,"Shahd El Yaseen, Shaila Sabt, Hala, Hanadi Al-...",NaN,"March 20, 2019",2018,TV-14,1 Season,"International TV Shows, TV Dramas","As a psychology professor faces Alzheimer's, h..."
16,s18,Movie,22-Jul,Paul Greengrass,"Anders Danielsen Lie, Jon Øigarden, Jonas Stra...","Norway, Iceland, United States","October 10, 2018",2018,R,144 min,"Dramas, Thrillers","After devastating terror attacks in Norway, a ..."
17,s19,Movie,15-Aug,Swapnaneel Jayakar,"Rahul Pethe, Mrunmayee Deshpande, Adinath Koth...",India,"March 29, 2019",2019,TV-14,124 min,"Comedies, Dramas, Independent Movies","On India's Independence Day, a zany mishap in ..."
18,s20,Movie,'89,NaN,"Lee Dixon, Ian Wright, Paul Merson",United Kingdom,"May 16, 2018",2017,TV-PG,87 min,Sports Movies,"Mixing old footage with interviews, this is th..."
19,s21,Movie,​​Kuch Bheege Alfaaz,Onir,"Geetanjali Thapa, Zain Khan Durrani, Shray Rai...",India,"September 1, 2018",2018,TV-14,110 min,"Dramas, Independent Movies, International Movies",After accidentally connecting over the Interne...
20,s22,Movie,​Goli Soda 2,Vijay Milton,"Samuthirakani, Bharath Seeni, Vinoth, Esakki B...",India,"September 15, 2018",2018,TV-14,128 min,"Action & Adventure, Dramas, International Movies","A taxi driver, a gangster and an athlete strug..."
21,s23,Movie,​Maj Rati ​​Keteki,Santwana Bardoloi,"Adil Hussain, Shakil Imtiaz, Mahendra Rabha, S...",India,"September 15, 2018",2017,TV-14,117 min,"Dramas, International Movies",A successful writer returns to the town that l...
22,s24,Movie,​Mayurakshi,Atanu Ghosh,"Soumitra Chatterjee, Prasenjit Chatterjee, Ind...",India,"September 15, 2018",2017,TV-14,100 min,"Dramas, International Movies",When a middle-aged divorcee returns to Kolkata...
23,s25,TV Show,​SAINT SEIYA: Knights of the Zodiac,NaN,"Bryson Baugus, Emily Neves, Blake Shepard, Pat...",Japan,"January 23, 2020",2020,TV-14,2 Seasons,"Anime Series, International TV Shows",Seiya and the Knights of the Zodiac rise again...
24,s26,Movie,(T)ERROR,"Lyric R. Cabral, David Felix Sutcliffe",NaN,United States,"June 30, 2016",2015,NR,84 min,Documentaries,This real-life look at FBI counterterrorism op...
25,s27,TV Show,(Un)Well,NaN,NaN,United States,"August 12, 2020",2020,TV-MA,1 Season,Reality TV,This docuseries takes a deep dive into the luc...
26,s28,Movie,#Alive,Cho Il,"Yoo Ah-in, Park Shin-hye",South Korea,"September 8, 2020",2020,TV-MA,99 min,"Horror Movies, International Movies, Thrillers","As a grisly virus rampages a city, a lone man ..."
27,s29,Movie,#AnneFrank - Parallel Stories,"Sabina Fedeli, Anna Migotto","Helen Mirren, Gengher Gatti",Italy,"July 1, 2020",2019,TV-14,95 min,"Documentaries, International Movies","Through her diary, Anne Frank's story is retol..."
28,s30,TV Show,#blackAF,NaN,"Kenya Barris, Rashida Jones, Iman Benson, Genn...",United States,"April 17, 2020",2020,TV-MA,1 Season,TV Comedies,Kenya Barris and his family navigate relations...
29,s31,Movie,#cats_the_mewvie,Michael Margolis,NaN,Canada,"February 5, 2020",2020,TV-14,90 min,"Documentaries, International Movies",This pawesome documentary explores how our fel...
...,...,...,...,...,...,...,...,...,...,...,...,...
1023,s1025,Movie,Boi,Jorge M. Fontana,"Bernat Quintana, Adrian Pang, Andrew Lua, Rach...",Spain,"July 26, 2019",2018,TV-MA,111 min,"Dramas, Independent Movies, International Movies",A young chauffeur who's at a crossroads in his...
1024,s1026,TV Show,BoJack Horseman,NaN,"Will Arnett, Aaron Paul, Amy Sedaris, Alison B...",United States,"October 25, 2019",2020,TV-MA,6 Seasons,TV Comedies,Meet the most beloved sitcom horse of the '90s...
1025,s1027,Movie,BoJack Horseman Christmas Special: Sabrina's C...,NaN,"Will Arnett, Aaron Paul, Alison Brie, Adam Con...",United States,"December 19, 2014",2014,TV-MA,26 min,Movies,"It's Christmas, and BoJack wants nothing to do..."
1026,s1028,Movie,Bokeh,"Geoffrey Orthwein, Andrew Sullivan","Maika Monroe, Matt O'Leary, Arnar Jónsson, Gun...","United States, Iceland","June 22, 2017",2017,TV-14,92 min,"Dramas, Independent Movies, Sci-Fi & Fantasy",After learning they are the sole survivors of ...
1027,s1029,TV Show,Bolívar,"Luis Alberto Restrepo, Andrés Beltrán, Jaime Rayo","Luis Gerónimo Abreu, José Ramón Barreto, Ernes...",Colombia,"June 21, 2019",2019,TV-MA,1 Season,"International TV Shows, Romantic TV Shows, Spa...",This dramatization depicts the life – and love...
1028,s1030,Movie,Bollywood Calling,Nagesh Kukunoor,"Om Puri, Pat Cusick, Navin Nischol, Perizaad Z...",India,"April 15, 2019",2001,TV-MA,102 min,"Comedies, Dramas, International Movies",A down-and-out Hollywood actor is utterly unpr...
1029,s1031,Movie,Bolt,"Byron Howard, Chris Williams","John Travolta, Miley Cyrus, Susie Essman, Mark...",United States,"July 22, 2018",2008,PG,99 min,"Children & Family Movies, Comedies","This tale follows German shepherd Bolt, a cani..."
1030,s1032,Movie,Bomb Scared,Borja Cobeaga,"Javier Cámara, Julián López, Miren Ibarguren, ...",Spain,"October 12, 2017",2017,TV-MA,89 min,"Comedies, Independent Movies, International Mo...","In this dark comedy, a dysfunctional group of ..."
1031,s1033,Movie,Bombairiya,Pia Sukanya,"Radhika Apte, Siddhant Kapoor, Akshay Oberoi, ...","United Arab Emirates, United Kingdom, India","March 15, 2019",2018,TV-MA,108 min,"Comedies, Dramas, International Movies","A PR agent trying to find her stolen phone, a ..."
1032,s1034,Movie,Bombay Talkies,"Anurag Kashyap, Dibakar Banerjee, Karan Johar,...","Rani Mukerji, Randeep Hooda, Saqib Saleem, Naw...",India,"July 5, 2020",2013,TV-MA,123 min,"Dramas, International Movies","A gay man deals with his sexuality, a struggli..."
1033,s1035,Movie,Bombshell,Riccardo Pilizzeri,"Ande Cunningham, Mark Mitchinson, Mia Pistoriu...",New Zealand,"October 1, 2016",2016,TV-MA,86 min,Dramas,"In 1985, when a vessel protesting nuclear test..."
1034,s1036,Movie,Bombshell: The Hedy Lamarr Story,Alexandra Dean,Hedy Lamarr,United States,"May 31, 2018",2017,TV-14,89 min,Documentaries,An unearthed audio interview of Hollywood icon...
1035,s1037,Movie,Bon Bini Holland,Jelle de Jonge,"Jandino Asporaat, Liliana de Vries, Teun Kuilb...",Netherlands,"September 1, 2016",2015,TV-MA,88 min,"Comedies, International Movies","On the island of Curaçao, an amiable scam arti..."
1036,s1038,Movie,Bon Cop Bad Cop 2,Alain Desrochers,"Patrick Huard, Colm Feore, Marc Beaupré, Noam ...",Canada,"November 11, 2017",2017,TV-MA,126 min,"Action & Adventure, Comedies, International Mo...",Two veteran buddy cops are back for a second c...
1037,s1039,Movie,"Bon Cop, Bad Cop",Erik Canuel,"Patrick Huard, Colm Feore, Sylvain Marcel, Luc...",Canada,"March 15, 2017",2006,TV-MA,117 min,"Action & Adventure, Comedies, International Mo...",An English-speaking officer from Toronto and a...
1038,s1040,TV Show,Bondi Rescue,NaN,"Andrew Günsberg, Dean Gladstone, Bruce Hopkins...",Australia,"November 1, 2019",2016,TV-PG,1 Season,Reality TV,This reality series follows elite professional...
1039,s1041,TV Show,BONDING,NaN,"Zoe Levin, Brendan Scannell, Micah Stock, Theo...",United States,"September 22, 2019",2019,TV-MA,1 Season,"TV Comedies, TV Dramas",A New York City grad student moonlighting as a...
1040,s1042,Movie,Bonnie and Clyde,Arthur Penn,"Warren Beatty, Faye Dunaway, Michael J. Pollar...",United States,"January 1, 2021",1967,R,111 min,"Action & Adventure, Classic Movies, Dramas","Bonnie Parker and Clyde Barrow are young, in l..."
1041,s1043,TV Show,Bonus Family,NaN,"Vera Vitali, Erik Johansson, Fredrik Hallgren,...",Sweden,"July 12, 2019",2019,TV-MA,3 Seasons,"International TV Shows, TV Dramas","A new couple, their exes and their children na..."
1042,s1044,TV Show,Booba,NaN,Roman Karev,Russia,"January 16, 2020",2019,TV-Y7,3 Seasons,"Kids' TV, TV Comedies",The world is a mystery to little Booba. But he...
1043,s1045,TV Show,Bookmarks,NaN,Marley Dias,United States,"September 1, 2020",2020,TV-Y,1 Season,Kids' TV,Celebrity readers share children's books by Bl...
1044,s1046,Movie,Boom,Kaizad Gustad,"Amitabh Bachchan, Gulshan Grover, Jackie Shrof...",India,"March 1, 2018",2003,TV-MA,79 min,"Action & Adventure, Dramas, International Movies","Following a fashion show mishap, three supermo..."
1045,s1047,TV Show,Border Patrol,NaN,Timothy Balme,NaN,"October 2, 2019",2016,TV-PG,1 Season,Reality TV,This reality TV series follows the men and wom...
1046,s1048,TV Show,Border Security: America's Front Line,NaN,NaN,Canada,"January 1, 2020",2018,TV-14,1 Season,"Crime TV Shows, International TV Shows, Realit...",This reality series chronicles the behind-the-...
1047,s1049,TV Show,Borderline,NaN,"David Avery, Jackie Clune, David Elms, Liz Kin...",United Kingdom,"December 2, 2017",2017,TV-14,2 Seasons,"British TV Shows, TV Comedies",A team of inept border agents tackles immigrat...
1048,s1050,TV Show,Borderliner,NaN,"Tobias Santelmann, Ellen Dorrit Petersen, Benj...","Norway, Germany, Sweden","March 6, 2018",2017,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas","To protect his family, a police detective cove..."
1049,s1051,TV Show,Bordertown,NaN,"Ville Virtanen, Matleena Kuusniemi, Anu Sinisa...","Finland, France","May 11, 2020",2019,TV-MA,3 Seasons,"Crime TV Shows, International TV Shows, TV Dramas",A gifted detective takes a job in a small town...
1050,s1052,TV Show,Borgen,NaN,"Sidse Babett Knudsen, Birgitte Hjort Sørensen,...",Denmark,"September 1, 2020",2012,TV-MA,3 Seasons,"International TV Shows, TV Dramas",A shocking turn of events puts Birgitte Nyborg...
1051,s1053,TV Show,Borges,NaN,"Thati Lopes, Antonio Pedro Tabet, Karina Ramil...",Brazil,"June 25, 2018",2018,TV-MA,1 Season,"International TV Shows, TV Comedies",Left deeply in debt after their boss flees the...
1052,s1054,Movie,Born Beautiful,Perci Intalan,"Martin del Rosario, Lou Veloso, Chai Fonacier,...",Philippines,"April 8, 2020",2019,TV-MA,96 min,"Comedies, Dramas, International Movies","After her best friend dies, Barbs attempts to ..."

In [20]:
db.info

<bound method DataFrame.info of          s1  TV Show                                                 3%  \
0        s2    Movie                                               7:19
1        s3    Movie                                              23:59
2        s4    Movie                                                  9
3        s5    Movie                                                 21
4        s6  TV Show                                                 46
5        s7    Movie                                                122
6        s8    Movie                                                187
7        s9    Movie                                                706
8       s10    Movie                                               1920
9       s11    Movie                                               1922
10      s12  TV Show                                               1983
11      s13  TV Show                                               1994
12      s14    Movie                                               2215
13      s15    Movie                                               3022
14      s16    Movie                                             Oct-01
15      s17  TV Show                                             Feb-09
16      s18    Movie                                             22-Jul
17      s19    Movie                                             15-Aug
18      s20    Movie                                                '89
19      s21    Movie                               ​​Kuch Bheege Alfaaz
20      s22    Movie                                       ​Goli Soda 2
21      s23    Movie                                 ​Maj Rati ​​Keteki
22      s24    Movie                                        ​Mayurakshi
23      s25  TV Show                ​SAINT SEIYA: Knights of the Zodiac
24      s26    Movie                                           (T)ERROR
25      s27  TV Show                                           (Un)Well
26      s28    Movie                                             #Alive
27      s29    Movie                      #AnneFrank - Parallel Stories
28      s30  TV Show                                           #blackAF
29      s31    Movie                                   #cats_the_mewvie
...     ...      ...                                                ...
1023  s1025    Movie                                                Boi
1024  s1026  TV Show                                    BoJack Horseman
1025  s1027    Movie  BoJack Horseman Christmas Special: Sabrina's C...
1026  s1028    Movie                                              Bokeh
1027  s1029  TV Show                                            Bolívar
1028  s1030    Movie                                  Bollywood Calling
1029  s1031    Movie                                               Bolt
1030  s1032    Movie                                        Bomb Scared
1031  s1033    Movie                                         Bombairiya
1032  s1034    Movie                                     Bombay Talkies
1033  s1035    Movie                                          Bombshell
1034  s1036    Movie                   Bombshell: The Hedy Lamarr Story
1035  s1037    Movie                                   Bon Bini Holland
1036  s1038    Movie                                  Bon Cop Bad Cop 2
1037  s1039    Movie                                   Bon Cop, Bad Cop
1038  s1040  TV Show                                       Bondi Rescue
1039  s1041  TV Show                                            BONDING
1040  s1042    Movie                                   Bonnie and Clyde
1041  s1043  TV Show                                       Bonus Family
1042  s1044  TV Show                                              Booba
1043  s1045  TV Show                                          Bookmarks
1044  s1046    Movie                                               Boom
1045  s1047  TV Show                                      Border Patrol
1046  s1048  TV Show              Border Security: America's Front Line
1047  s1049  TV Show                                         Borderline
1048  s1050  TV Show                                        Borderliner
1049  s1051  TV Show                                         Bordertown
1050  s1052  TV Show                                             Borgen
1051  s1053  TV Show                                             Borges
1052  s1054    Movie                                     Born Beautiful

                                             Unnamed: 3  \
0                                     Jorge Michel Grau
1                                          Gilbert Chan
2                                           Shane Acker
3                                        Robert Luketic
4                                           Serdar Akar
5                                       Yasir Al Yasiri
6                                        Kevin Reynolds
7                                         Shravan Kumar
8                                          Vikram Bhatt
9                                          Zak Hilditch
10                                                  NaN
11                                 Diego Enrique Osorno
12                                  Nottapon Boonprakob
13                                           John Suits
14                                       Kunle Afolayan
15                                                  NaN
16                                      Paul Greengrass
17                                   Swapnaneel Jayakar
18                                                  NaN
19                                                 Onir
20                                         Vijay Milton
21                                    Santwana Bardoloi
22                                          Atanu Ghosh
23                                                  NaN
24               Lyric R. Cabral, David Felix Sutcliffe
25                                                  NaN
26                                               Cho Il
27                          Sabina Fedeli, Anna Migotto
28                                                  NaN
29                                     Michael Margolis
...                                                 ...
1023                                   Jorge M. Fontana
1024                                                NaN
1025                                                NaN
1026                 Geoffrey Orthwein, Andrew Sullivan
1027  Luis Alberto Restrepo, Andrés Beltrán, Jaime Rayo
1028                                    Nagesh Kukunoor
1029                       Byron Howard, Chris Williams
1030                                      Borja Cobeaga
1031                                        Pia Sukanya
1032  Anurag Kashyap, Dibakar Banerjee, Karan Johar,...
1033                                 Riccardo Pilizzeri
1034                                     Alexandra Dean
1035                                     Jelle de Jonge
1036                                   Alain Desrochers
1037                                        Erik Canuel
1038                                                NaN
1039                                                NaN
1040                                        Arthur Penn
1041                                                NaN
1042                                                NaN
1043                                                NaN
1044                                      Kaizad Gustad
1045                                                NaN
1046                                                NaN
1047                                                NaN
1048                                                NaN
1049                                                NaN
1050                                                NaN
1051                                                NaN
1052                                      Perci Intalan

     João Miguel, Bianca Comparato, Michel Gomes, Rodolfo Valente, Vaneza Oliveira, Rafael Lozano, Viviane Porto, Mel Fronckowiak, Sergio Mamberti, Zezé Motta, Celso Frateschi  \
0     Demián Bichir, Héctor Bonilla, Oscar Serrano, ...
1     Tedd Chan, Stella Chung, Henley Hii, Lawrence ...
2     Elijah Wood, John C. Reilly, Jennifer Connelly...
3     Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...
4     Erdal Beşikçioğlu, Yasemin Allen, Melis Birkan...
5     Amina Khalil, Ahmed Dawood, Tarek Lotfy, Ahmed...
6     Samuel L. Jackson, John Heard, Kelly Rowan, Cl...
7     Divya Dutta, Atul Kulkarni, Mohan Agashe, Anup...
8     Rajneesh Duggal, Adah Sharma, Indraneil Sengup...
9     Thomas Jane, Molly Parker, Dylan Schmid, Kaitl...
10    Robert Więckiewicz, Maciej Musiał, Michalina O...
11                                                  NaN
12                                   Artiwara Kongmalai
13    Omar Epps, Kate Walsh, Miranda Cosgrove, Angus...
14    Sadiq Daba, David Bailie, Kayode Olaiya, Kehin...
15    Shahd El Yaseen, Shaila Sabt, Hala, Hanadi Al-...
16    Anders Danielsen Lie, Jon Øigarden, Jonas Stra...
17    Rahul Pethe, Mrunmayee Deshpande, Adinath Koth...
18                   Lee Dixon, Ian Wright, Paul Merson
19    Geetanjali Thapa, Zain Khan Durrani, Shray Rai...
20    Samuthirakani, Bharath Seeni, Vinoth, Esakki B...
21    Adil Hussain, Shakil Imtiaz, Mahendra Rabha, S...
22    Soumitra Chatterjee, Prasenjit Chatterjee, Ind...
23    Bryson Baugus, Emily Neves, Blake Shepard, Pat...
24                                                  NaN
25                                                  NaN
26                             Yoo Ah-in, Park Shin-hye
27                          Helen Mirren, Gengher Gatti
28    Kenya Barris, Rashida Jones, Iman Benson, Genn...
29                                                  NaN
...                                                 ...
1023  Bernat Quintana, Adrian Pang, Andrew Lua, Rach...
1024  Will Arnett, Aaron Paul, Amy Sedaris, Alison B...
1025  Will Arnett, Aaron Paul, Alison Brie, Adam Con...
1026  Maika Monroe, Matt O'Leary, Arnar Jónsson, Gun...
1027  Luis Gerónimo Abreu, José Ramón Barreto, Ernes...
1028  Om Puri, Pat Cusick, Navin Nischol, Perizaad Z...
1029  John Travolta, Miley Cyrus, Susie Essman, Mark...
1030  Javier Cámara, Julián López, Miren Ibarguren, ...
1031  Radhika Apte, Siddhant Kapoor, Akshay Oberoi, ...
1032  Rani Mukerji, Randeep Hooda, Saqib Saleem, Naw...
1033  Ande Cunningham, Mark Mitchinson, Mia Pistoriu...
1034                                        Hedy Lamarr
1035  Jandino Asporaat, Liliana de Vries, Teun Kuilb...
1036  Patrick Huard, Colm Feore, Marc Beaupré, Noam ...
1037  Patrick Huard, Colm Feore, Sylvain Marcel, Luc...
1038  Andrew Günsberg, Dean Gladstone, Bruce Hopkins...
1039  Zoe Levin, Brendan Scannell, Micah Stock, Theo...
1040  Warren Beatty, Faye Dunaway, Michael J. Pollar...
1041  Vera Vitali, Erik Johansson, Fredrik Hallgren,...
1042                                        Roman Karev
1043                                        Marley Dias
1044  Amitabh Bachchan, Gulshan Grover, Jackie Shrof...
1045                                      Timothy Balme
1046                                                NaN
1047  David Avery, Jackie Clune, David Elms, Liz Kin...
1048  Tobias Santelmann, Ellen Dorrit Petersen, Benj...
1049  Ville Virtanen, Matleena Kuusniemi, Anu Sinisa...
1050  Sidse Babett Knudsen, Birgitte Hjort Sørensen,...
1051  Thati Lopes, Antonio Pedro Tabet, Karina Ramil...
1052  Martin del Rosario, Lou Veloso, Chai Fonacier,...

                                           Brazil     August 14, 2020  2020  \
0                                          Mexico   December 23, 2016  2016
1                                       Singapore   December 20, 2018  2011
2                                   United States   November 16, 2017  2009
3                                   United States     January 1, 2020  2008
4                                          Turkey        July 1, 2017  2016
5                                           Egypt        June 1, 2020  2019
6                                   United States    November 1, 2019  1997
7                                           India       April 1, 2019  2019
8                                           India   December 15, 2017  2008
9                                   United States    October 20, 2017  2017
10                          Poland, United States   November 30, 2018  2018
11                                         Mexico        May 17, 2019  2019
12                                       Thailand       March 1, 2019  2018
13                                  United States      March 19, 2020  2019
14                                        Nigeria   September 1, 2019  2014
15                                            NaN      March 20, 2019  2018
16                 Norway, Iceland, United States    October 10, 2018  2018
17                                          India      March 29, 2019  2019
18                                 United Kingdom        May 16, 2018  2017
19                                          India   September 1, 2018  2018
20                                          India  September 15, 2018  2018
21                                          India  September 15, 2018  2017
22                                          India  September 15, 2018  2017
23                                          Japan    January 23, 2020  2020
24                                  United States       June 30, 2016  2015
25                                  United States     August 12, 2020  2020
26                                    South Korea   September 8, 2020  2020
27                                          Italy        July 1, 2020  2019
28                                  United States      April 17, 2020  2020
29                                         Canada    February 5, 2020  2020
...                                           ...                 ...   ...
1023                                        Spain       July 26, 2019  2018
1024                                United States    October 25, 2019  2020
1025                                United States   December 19, 2014  2014
1026                       United States, Iceland       June 22, 2017  2017
1027                                     Colombia       June 21, 2019  2019
1028                                        India      April 15, 2019  2001
1029                                United States       July 22, 2018  2008
1030                                        Spain    October 12, 2017  2017
1031  United Arab Emirates, United Kingdom, India      March 15, 2019  2018
1032                                        India        July 5, 2020  2013
1033                                  New Zealand     October 1, 2016  2016
1034                                United States        May 31, 2018  2017
1035                                  Netherlands   September 1, 2016  2015
1036                                       Canada   November 11, 2017  2017
1037                                       Canada      March 15, 2017  2006
1038                                    Australia    November 1, 2019  2016
1039                                United States  September 22, 2019  2019
1040                                United States     January 1, 2021  1967
1041                                       Sweden       July 12, 2019  2019
1042                                       Russia    January 16, 2020  2019
1043                                United States   September 1, 2020  2020
1044                                        India       March 1, 2018  2003
1045                                          NaN     October 2, 2019  2016
1046                                       Canada     January 1, 2020  2018
1047                               United Kingdom    December 2, 2017  2017
1048                      Norway, Germany, Sweden       March 6, 2018  2017
1049                              Finland, France        May 11, 2020  2019
1050                                      Denmark   September 1, 2020  2012
1051                                       Brazil       June 25, 2018  2018
1052                                  Philippines       April 8, 2020  2019

      TV-MA  4 Seasons International TV Shows, TV Dramas, TV Sci-Fi & Fantasy  \
0     TV-MA     93 min                       Dramas, International Movies
1         R     78 min                Horror Movies, International Movies
2     PG-13     80 min  Action & Adventure, Independent Movies, Sci-Fi...
3     PG-13    123 min                                             Dramas
4     TV-MA   1 Season    International TV Shows, TV Dramas, TV Mysteries
5     TV-MA     95 min                Horror Movies, International Movies
6         R    119 min                                             Dramas
7     TV-14    118 min                Horror Movies, International Movies
8     TV-MA    143 min     Horror Movies, International Movies, Thrillers
9     TV-MA    103 min                                  Dramas, Thrillers
10    TV-MA   1 Season  Crime TV Shows, International TV Shows, TV Dramas
11    TV-MA   1 Season  Crime TV Shows, Docuseries, International TV S...
12    TV-MA     89 min  Documentaries, International Movies, Sports Mo...
13        R     91 min    Independent Movies, Sci-Fi & Fantasy, Thrillers
14    TV-14    149 min            Dramas, International Movies, Thrillers
15    TV-14   1 Season                  International TV Shows, TV Dramas
16        R    144 min                                  Dramas, Thrillers
17    TV-14    124 min               Comedies, Dramas, Independent Movies
18    TV-PG     87 min                                      Sports Movies
19    TV-14    110 min   Dramas, Independent Movies, International Movies
20    TV-14    128 min   Action & Adventure, Dramas, International Movies
21    TV-14    117 min                       Dramas, International Movies
22    TV-14    100 min                       Dramas, International Movies
23    TV-14  2 Seasons               Anime Series, International TV Shows
24       NR     84 min                                      Documentaries
25    TV-MA   1 Season                                         Reality TV
26    TV-MA     99 min     Horror Movies, International Movies, Thrillers
27    TV-14     95 min                Documentaries, International Movies
28    TV-MA   1 Season                                        TV Comedies
29    TV-14     90 min                Documentaries, International Movies
...     ...        ...                                                ...
1023  TV-MA    111 min   Dramas, Independent Movies, International Movies
1024  TV-MA  6 Seasons                                        TV Comedies
1025  TV-MA     26 min                                             Movies
1026  TV-14     92 min       Dramas, Independent Movies, Sci-Fi & Fantasy
1027  TV-MA   1 Season  International TV Shows, Romantic TV Shows, Spa...
1028  TV-MA    102 min             Comedies, Dramas, International Movies
1029     PG     99 min                 Children & Family Movies, Comedies
1030  TV-MA     89 min  Comedies, Independent Movies, International Mo...
1031  TV-MA    108 min             Comedies, Dramas, International Movies
1032  TV-MA    123 min                       Dramas, International Movies
1033  TV-MA     86 min                                             Dramas
1034  TV-14     89 min                                      Documentaries
1035  TV-MA     88 min                     Comedies, International Movies
1036  TV-MA    126 min  Action & Adventure, Comedies, International Mo...
1037  TV-MA    117 min  Action & Adventure, Comedies, International Mo...
1038  TV-PG   1 Season                                         Reality TV
1039  TV-MA   1 Season                             TV Comedies, TV Dramas
1040      R    111 min         Action & Adventure, Classic Movies, Dramas

In [21]:
db.count

<bound method DataFrame.count of          s1  TV Show                                                 3%  \
0        s2    Movie                                               7:19
1        s3    Movie                                              23:59
2        s4    Movie                                                  9
3        s5    Movie                                                 21
4        s6  TV Show                                                 46
5        s7    Movie                                                122
6        s8    Movie                                                187
7        s9    Movie                                                706
8       s10    Movie                                               1920
9       s11    Movie                                               1922
10      s12  TV Show                                               1983
11      s13  TV Show                                               1994
12      s14    Movie                                               2215
13      s15    Movie                                               3022
14      s16    Movie                                             Oct-01
15      s17  TV Show                                             Feb-09
16      s18    Movie                                             22-Jul
17      s19    Movie                                             15-Aug
18      s20    Movie                                                '89
19      s21    Movie                               ​​Kuch Bheege Alfaaz
20      s22    Movie                                       ​Goli Soda 2
21      s23    Movie                                 ​Maj Rati ​​Keteki
22      s24    Movie                                        ​Mayurakshi
23      s25  TV Show                ​SAINT SEIYA: Knights of the Zodiac
24      s26    Movie                                           (T)ERROR
25      s27  TV Show                                           (Un)Well
26      s28    Movie                                             #Alive
27      s29    Movie                      #AnneFrank - Parallel Stories
28      s30  TV Show                                           #blackAF
29      s31    Movie                                   #cats_the_mewvie
...     ...      ...                                                ...
1023  s1025    Movie                                                Boi
1024  s1026  TV Show                                    BoJack Horseman
1025  s1027    Movie  BoJack Horseman Christmas Special: Sabrina's C...
1026  s1028    Movie                                              Bokeh
1027  s1029  TV Show                                            Bolívar
1028  s1030    Movie                                  Bollywood Calling
1029  s1031    Movie                                               Bolt
1030  s1032    Movie                                        Bomb Scared
1031  s1033    Movie                                         Bombairiya
1032  s1034    Movie                                     Bombay Talkies
1033  s1035    Movie                                          Bombshell
1034  s1036    Movie                   Bombshell: The Hedy Lamarr Story
1035  s1037    Movie                                   Bon Bini Holland
1036  s1038    Movie                                  Bon Cop Bad Cop 2
1037  s1039    Movie                                   Bon Cop, Bad Cop
1038  s1040  TV Show                                       Bondi Rescue
1039  s1041  TV Show                                            BONDING
1040  s1042    Movie                                   Bonnie and Clyde
1041  s1043  TV Show                                       Bonus Family
1042  s1044  TV Show                                              Booba
1043  s1045  TV Show                                          Bookmarks
1044  s1046    Movie                                               Boom
1045  s1047  TV Show                                      Border Patrol
1046  s1048  TV Show              Border Security: America's Front Line
1047  s1049  TV Show                                         Borderline
1048  s1050  TV Show                                        Borderliner
1049  s1051  TV Show                                         Bordertown
1050  s1052  TV Show                                             Borgen
1051  s1053  TV Show                                             Borges
1052  s1054    Movie                                     Born Beautiful

                                             Unnamed: 3  \
0                                     Jorge Michel Grau
1                                          Gilbert Chan
2                                           Shane Acker
3                                        Robert Luketic
4                                           Serdar Akar
5                                       Yasir Al Yasiri
6                                        Kevin Reynolds
7                                         Shravan Kumar
8                                          Vikram Bhatt
9                                          Zak Hilditch
10                                                  NaN
11                                 Diego Enrique Osorno
12                                  Nottapon Boonprakob
13                                           John Suits
14                                       Kunle Afolayan
15                                                  NaN
16                                      Paul Greengrass
17                                   Swapnaneel Jayakar
18                                                  NaN
19                                                 Onir
20                                         Vijay Milton
21                                    Santwana Bardoloi
22                                          Atanu Ghosh
23                                                  NaN
24               Lyric R. Cabral, David Felix Sutcliffe
25                                                  NaN
26                                               Cho Il
27                          Sabina Fedeli, Anna Migotto
28                                                  NaN
29                                     Michael Margolis
...                                                 ...
1023                                   Jorge M. Fontana
1024                                                NaN
1025                                                NaN
1026                 Geoffrey Orthwein, Andrew Sullivan
1027  Luis Alberto Restrepo, Andrés Beltrán, Jaime Rayo
1028                                    Nagesh Kukunoor
1029                       Byron Howard, Chris Williams
1030                                      Borja Cobeaga
1031                                        Pia Sukanya
1032  Anurag Kashyap, Dibakar Banerjee, Karan Johar,...
1033                                 Riccardo Pilizzeri
1034                                     Alexandra Dean
1035                                     Jelle de Jonge
1036                                   Alain Desrochers
1037                                        Erik Canuel
1038                                                NaN
1039                                                NaN
1040                                        Arthur Penn
1041                                                NaN
1042                                                NaN
1043                                                NaN
1044                                      Kaizad Gustad
1045                                                NaN
1046                                                NaN
1047                                                NaN
1048                                                NaN
1049                                                NaN
1050                                                NaN
1051                                                NaN
1052                                      Perci Intalan

     João Miguel, Bianca Comparato, Michel Gomes, Rodolfo Valente, Vaneza Oliveira, Rafael Lozano, Viviane Porto, Mel Fronckowiak, Sergio Mamberti, Zezé Motta, Celso Frateschi  \
0     Demián Bichir, Héctor Bonilla, Oscar Serrano, ...
1     Tedd Chan, Stella Chung, Henley Hii, Lawrence ...
2     Elijah Wood, John C. Reilly, Jennifer Connelly...
3     Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...
4     Erdal Beşikçioğlu, Yasemin Allen, Melis Birkan...
5     Amina Khalil, Ahmed Dawood, Tarek Lotfy, Ahmed...
6     Samuel L. Jackson, John Heard, Kelly Rowan, Cl...
7     Divya Dutta, Atul Kulkarni, Mohan Agashe, Anup...
8     Rajneesh Duggal, Adah Sharma, Indraneil Sengup...
9     Thomas Jane, Molly Parker, Dylan Schmid, Kaitl...
10    Robert Więckiewicz, Maciej Musiał, Michalina O...
11                                                  NaN
12                                   Artiwara Kongmalai
13    Omar Epps, Kate Walsh, Miranda Cosgrove, Angus...
14    Sadiq Daba, David Bailie, Kayode Olaiya, Kehin...
15    Shahd El Yaseen, Shaila Sabt, Hala, Hanadi Al-...
16    Anders Danielsen Lie, Jon Øigarden, Jonas Stra...
17    Rahul Pethe, Mrunmayee Deshpande, Adinath Koth...
18                   Lee Dixon, Ian Wright, Paul Merson
19    Geetanjali Thapa, Zain Khan Durrani, Shray Rai...
20    Samuthirakani, Bharath Seeni, Vinoth, Esakki B...
21    Adil Hussain, Shakil Imtiaz, Mahendra Rabha, S...
22    Soumitra Chatterjee, Prasenjit Chatterjee, Ind...
23    Bryson Baugus, Emily Neves, Blake Shepard, Pat...
24                                                  NaN
25                                                  NaN
26                             Yoo Ah-in, Park Shin-hye
27                          Helen Mirren, Gengher Gatti
28    Kenya Barris, Rashida Jones, Iman Benson, Genn...
29                                                  NaN
...                                                 ...
1023  Bernat Quintana, Adrian Pang, Andrew Lua, Rach...
1024  Will Arnett, Aaron Paul, Amy Sedaris, Alison B...
1025  Will Arnett, Aaron Paul, Alison Brie, Adam Con...
1026  Maika Monroe, Matt O'Leary, Arnar Jónsson, Gun...
1027  Luis Gerónimo Abreu, José Ramón Barreto, Ernes...
1028  Om Puri, Pat Cusick, Navin Nischol, Perizaad Z...
1029  John Travolta, Miley Cyrus, Susie Essman, Mark...
1030  Javier Cámara, Julián López, Miren Ibarguren, ...
1031  Radhika Apte, Siddhant Kapoor, Akshay Oberoi, ...
1032  Rani Mukerji, Randeep Hooda, Saqib Saleem, Naw...
1033  Ande Cunningham, Mark Mitchinson, Mia Pistoriu...
1034                                        Hedy Lamarr
1035  Jandino Asporaat, Liliana de Vries, Teun Kuilb...
1036  Patrick Huard, Colm Feore, Marc Beaupré, Noam ...
1037  Patrick Huard, Colm Feore, Sylvain Marcel, Luc...
1038  Andrew Günsberg, Dean Gladstone, Bruce Hopkins...
1039  Zoe Levin, Brendan Scannell, Micah Stock, Theo...
1040  Warren Beatty, Faye Dunaway, Michael J. Pollar...
1041  Vera Vitali, Erik Johansson, Fredrik Hallgren,...
1042                                        Roman Karev
1043                                        Marley Dias
1044  Amitabh Bachchan, Gulshan Grover, Jackie Shrof...
1045                                      Timothy Balme
1046                                                NaN
1047  David Avery, Jackie Clune, David Elms, Liz Kin...
1048  Tobias Santelmann, Ellen Dorrit Petersen, Benj...
1049  Ville Virtanen, Matleena Kuusniemi, Anu Sinisa...
1050  Sidse Babett Knudsen, Birgitte Hjort Sørensen,...
1051  Thati Lopes, Antonio Pedro Tabet, Karina Ramil...
1052  Martin del Rosario, Lou Veloso, Chai Fonacier,...

                                           Brazil     August 14, 2020  2020  \
0                                          Mexico   December 23, 2016  2016
1                                       Singapore   December 20, 2018  2011
2                                   United States   November 16, 2017  2009
3                                   United States     January 1, 2020  2008
4                                          Turkey        July 1, 2017  2016
5                                           Egypt        June 1, 2020  2019
6                                   United States    November 1, 2019  1997
7                                           India       April 1, 2019  2019
8                                           India   December 15, 2017  2008
9                                   United States    October 20, 2017  2017
10                          Poland, United States   November 30, 2018  2018
11                                         Mexico        May 17, 2019  2019
12                                       Thailand       March 1, 2019  2018
13                                  United States      March 19, 2020  2019
14                                        Nigeria   September 1, 2019  2014
15                                            NaN      March 20, 2019  2018
16                 Norway, Iceland, United States    October 10, 2018  2018
17                                          India      March 29, 2019  2019
18                                 United Kingdom        May 16, 2018  2017
19                                          India   September 1, 2018  2018
20                                          India  September 15, 2018  2018
21                                          India  September 15, 2018  2017
22                                          India  September 15, 2018  2017
23                                          Japan    January 23, 2020  2020
24                                  United States       June 30, 2016  2015
25                                  United States     August 12, 2020  2020
26                                    South Korea   September 8, 2020  2020
27                                          Italy        July 1, 2020  2019
28                                  United States      April 17, 2020  2020
29                                         Canada    February 5, 2020  2020
...                                           ...                 ...   ...
1023                                        Spain       July 26, 2019  2018
1024                                United States    October 25, 2019  2020
1025                                United States   December 19, 2014  2014
1026                       United States, Iceland       June 22, 2017  2017
1027                                     Colombia       June 21, 2019  2019
1028                                        India      April 15, 2019  2001
1029                                United States       July 22, 2018  2008
1030                                        Spain    October 12, 2017  2017
1031  United Arab Emirates, United Kingdom, India      March 15, 2019  2018
1032                                        India        July 5, 2020  2013
1033                                  New Zealand     October 1, 2016  2016
1034                                United States        May 31, 2018  2017
1035                                  Netherlands   September 1, 2016  2015
1036                                       Canada   November 11, 2017  2017
1037                                       Canada      March 15, 2017  2006
1038                                    Australia    November 1, 2019  2016
1039                                United States  September 22, 2019  2019
1040                                United States     January 1, 2021  1967
1041                                       Sweden       July 12, 2019  2019
1042                                       Russia    January 16, 2020  2019
1043                                United States   September 1, 2020  2020
1044                                        India       March 1, 2018  2003
1045                                          NaN     October 2, 2019  2016
1046                                       Canada     January 1, 2020  2018
1047                               United Kingdom    December 2, 2017  2017
1048                      Norway, Germany, Sweden       March 6, 2018  2017
1049                              Finland, France        May 11, 2020  2019
1050                                      Denmark   September 1, 2020  2012
1051                                       Brazil       June 25, 2018  2018
1052                                  Philippines       April 8, 2020  2019

      TV-MA  4 Seasons International TV Shows, TV Dramas, TV Sci-Fi & Fantasy  \
0     TV-MA     93 min                       Dramas, International Movies
1         R     78 min                Horror Movies, International Movies
2     PG-13     80 min  Action & Adventure, Independent Movies, Sci-Fi...
3     PG-13    123 min                                             Dramas
4     TV-MA   1 Season    International TV Shows, TV Dramas, TV Mysteries
5     TV-MA     95 min                Horror Movies, International Movies
6         R    119 min                                             Dramas
7     TV-14    118 min                Horror Movies, International Movies
8     TV-MA    143 min     Horror Movies, International Movies, Thrillers
9     TV-MA    103 min                                  Dramas, Thrillers
10    TV-MA   1 Season  Crime TV Shows, International TV Shows, TV Dramas
11    TV-MA   1 Season  Crime TV Shows, Docuseries, International TV S...
12    TV-MA     89 min  Documentaries, International Movies, Sports Mo...
13        R     91 min    Independent Movies, Sci-Fi & Fantasy, Thrillers
14    TV-14    149 min            Dramas, International Movies, Thrillers
15    TV-14   1 Season                  International TV Shows, TV Dramas
16        R    144 min                                  Dramas, Thrillers
17    TV-14    124 min               Comedies, Dramas, Independent Movies
18    TV-PG     87 min                                      Sports Movies
19    TV-14    110 min   Dramas, Independent Movies, International Movies
20    TV-14    128 min   Action & Adventure, Dramas, International Movies
21    TV-14    117 min                       Dramas, International Movies
22    TV-14    100 min                       Dramas, International Movies
23    TV-14  2 Seasons               Anime Series, International TV Shows
24       NR     84 min                                      Documentaries
25    TV-MA   1 Season                                         Reality TV
26    TV-MA     99 min     Horror Movies, International Movies, Thrillers
27    TV-14     95 min                Documentaries, International Movies
28    TV-MA   1 Season                                        TV Comedies
29    TV-14     90 min                Documentaries, International Movies
...     ...        ...                                                ...
1023  TV-MA    111 min   Dramas, Independent Movies, International Movies
1024  TV-MA  6 Seasons                                        TV Comedies
1025  TV-MA     26 min                                             Movies
1026  TV-14     92 min       Dramas, Independent Movies, Sci-Fi & Fantasy
1027  TV-MA   1 Season  International TV Shows, Romantic TV Shows, Spa...
1028  TV-MA    102 min             Comedies, Dramas, International Movies
1029     PG     99 min                 Children & Family Movies, Comedies
1030  TV-MA     89 min  Comedies, Independent Movies, International Mo...
1031  TV-MA    108 min             Comedies, Dramas, International Movies
1032  TV-MA    123 min                       Dramas, International Movies
1033  TV-MA     86 min                                             Dramas
1034  TV-14     89 min                                      Documentaries
1035  TV-MA     88 min                     Comedies, International Movies
1036  TV-MA    126 min  Action & Adventure, Comedies, International Mo...
1037  TV-MA    117 min  Action & Adventure, Comedies, International Mo...
1038  TV-PG   1 Season                                         Reality TV
1039  TV-MA   1 Season                             TV Comedies, TV Dramas
1040      R    111 min         Action & Adventure, Classic Movies, Dramas

In [22]:
db.head()

,s1,TV Show,3%,Unnamed: 3,"João Miguel, Bianca Comparato, Michel Gomes, Rodolfo Valente, Vaneza Oliveira, Rafael Lozano, Viviane Porto, Mel Fronckowiak, Sergio Mamberti, Zezé Motta, Celso Frateschi",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi & Fantasy","In a future where the elite inhabit an island paradise far from the crowded slums, you get one chance to join the 3% saved from squalor."
0,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
1,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
2,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
3,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...
4,s6,TV Show,46,Serdar Akar,"Erdal Beşikçioğlu, Yasemin Allen, Melis Birkan...",Turkey,"July 1, 2017",2016,TV-MA,1 Season,"International TV Shows, TV Dramas, TV Mysteries",A genetics professor experiments with a treatm...

In [23]:
db.tail()

,s1,TV Show,3%,Unnamed: 3,"João Miguel, Bianca Comparato, Michel Gomes, Rodolfo Valente, Vaneza Oliveira, Rafael Lozano, Viviane Porto, Mel Fronckowiak, Sergio Mamberti, Zezé Motta, Celso Frateschi",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi & Fantasy","In a future where the elite inhabit an island paradise far from the crowded slums, you get one chance to join the 3% saved from squalor."
1048,s1050,TV Show,Borderliner,NaN,"Tobias Santelmann, Ellen Dorrit Petersen, Benj...","Norway, Germany, Sweden","March 6, 2018",2017,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas","To protect his family, a police detective cove..."
1049,s1051,TV Show,Bordertown,NaN,"Ville Virtanen, Matleena Kuusniemi, Anu Sinisa...","Finland, France","May 11, 2020",2019,TV-MA,3 Seasons,"Crime TV Shows, International TV Shows, TV Dramas",A gifted detective takes a job in a small town...
1050,s1052,TV Show,Borgen,NaN,"Sidse Babett Knudsen, Birgitte Hjort Sørensen,...",Denmark,"September 1, 2020",2012,TV-MA,3 Seasons,"International TV Shows, TV Dramas",A shocking turn of events puts Birgitte Nyborg...
1051,s1053,TV Show,Borges,NaN,"Thati Lopes, Antonio Pedro Tabet, Karina Ramil...",Brazil,"June 25, 2018",2018,TV-MA,1 Season,"International TV Shows, TV Comedies",Left deeply in debt after their boss flees the...
1052,s1054,Movie,Born Beautiful,Perci Intalan,"Martin del Rosario, Lou Veloso, Chai Fonacier,...",Philippines,"April 8, 2020",2019,TV-MA,96 min,"Comedies, Dramas, International Movies","After her best friend dies, Barbs attempts to ..."

In [24]:
db.head(6)

,s1,TV Show,3%,Unnamed: 3,"João Miguel, Bianca Comparato, Michel Gomes, Rodolfo Valente, Vaneza Oliveira, Rafael Lozano, Viviane Porto, Mel Fronckowiak, Sergio Mamberti, Zezé Motta, Celso Frateschi",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi & Fantasy","In a future where the elite inhabit an island paradise far from the crowded slums, you get one chance to join the 3% saved from squalor."
0,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
1,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
2,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
3,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...
4,s6,TV Show,46,Serdar Akar,"Erdal Beşikçioğlu, Yasemin Allen, Melis Birkan...",Turkey,"July 1, 2017",2016,TV-MA,1 Season,"International TV Shows, TV Dramas, TV Mysteries",A genetics professor experiments with a treatm...
5,s7,Movie,122,Yasir Al Yasiri,"Amina Khalil, Ahmed Dawood, Tarek Lotfy, Ahmed...",Egypt,"June 1, 2020",2019,TV-MA,95 min,"Horror Movies, International Movies","After an awful accident, a couple admitted to ..."

In [25]:
db.tail(6)

,s1,TV Show,3%,Unnamed: 3,"João Miguel, Bianca Comparato, Michel Gomes, Rodolfo Valente, Vaneza Oliveira, Rafael Lozano, Viviane Porto, Mel Fronckowiak, Sergio Mamberti, Zezé Motta, Celso Frateschi",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi & Fantasy","In a future where the elite inhabit an island paradise far from the crowded slums, you get one chance to join the 3% saved from squalor."
1047,s1049,TV Show,Borderline,NaN,"David Avery, Jackie Clune, David Elms, Liz Kin...",United Kingdom,"December 2, 2017",2017,TV-14,2 Seasons,"British TV Shows, TV Comedies",A team of inept border agents tackles immigrat...
1048,s1050,TV Show,Borderliner,NaN,"Tobias Santelmann, Ellen Dorrit Petersen, Benj...","Norway, Germany, Sweden","March 6, 2018",2017,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas","To protect his family, a police detective cove..."
1049,s1051,TV Show,Bordertown,NaN,"Ville Virtanen, Matleena Kuusniemi, Anu Sinisa...","Finland, France","May 11, 2020",2019,TV-MA,3 Seasons,"Crime TV Shows, International TV Shows, TV Dramas",A gifted detective takes a job in a small town...
1050,s1052,TV Show,Borgen,NaN,"Sidse Babett Knudsen, Birgitte Hjort Sørensen,...",Denmark,"September 1, 2020",2012,TV-MA,3 Seasons,"International TV Shows, TV Dramas",A shocking turn of events puts Birgitte Nyborg...
1051,s1053,TV Show,Borges,NaN,"Thati Lopes, Antonio Pedro Tabet, Karina Ramil...",Brazil,"June 25, 2018",2018,TV-MA,1 Season,"International TV Shows, TV Comedies",Left deeply in debt after their boss flees the...
1052,s1054,Movie,Born Beautiful,Perci Intalan,"Martin del Rosario, Lou Veloso, Chai Fonacier,...",Philippines,"April 8, 2020",2019,TV-MA,96 min,"Comedies, Dramas, International Movies","After her best friend dies, Barbs attempts to ..."

In [26]:
db[6:]

,s1,TV Show,3%,Unnamed: 3,"João Miguel, Bianca Comparato, Michel Gomes, Rodolfo Valente, Vaneza Oliveira, Rafael Lozano, Viviane Porto, Mel Fronckowiak, Sergio Mamberti, Zezé Motta, Celso Frateschi",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi & Fantasy","In a future where the elite inhabit an island paradise far from the crowded slums, you get one chance to join the 3% saved from squalor."
6,s8,Movie,187,Kevin Reynolds,"Samuel L. Jackson, John Heard, Kelly Rowan, Cl...",United States,"November 1, 2019",1997,R,119 min,Dramas,After one of his high school students attacks ...
7,s9,Movie,706,Shravan Kumar,"Divya Dutta, Atul Kulkarni, Mohan Agashe, Anup...",India,"April 1, 2019",2019,TV-14,118 min,"Horror Movies, International Movies","When a doctor goes missing, his psychiatrist w..."
8,s10,Movie,1920,Vikram Bhatt,"Rajneesh Duggal, Adah Sharma, Indraneil Sengup...",India,"December 15, 2017",2008,TV-MA,143 min,"Horror Movies, International Movies, Thrillers",An architect and his wife move into a castle t...
9,s11,Movie,1922,Zak Hilditch,"Thomas Jane, Molly Parker, Dylan Schmid, Kaitl...",United States,"October 20, 2017",2017,TV-MA,103 min,"Dramas, Thrillers",A farmer pens a confession admitting to his wi...
10,s12,TV Show,1983,NaN,"Robert Więckiewicz, Maciej Musiał, Michalina O...","Poland, United States","November 30, 2018",2018,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas","In this dark alt-history thriller, a naïve law..."
11,s13,TV Show,1994,Diego Enrique Osorno,NaN,Mexico,"May 17, 2019",2019,TV-MA,1 Season,"Crime TV Shows, Docuseries, International TV S...",Archival video and new interviews examine Mexi...
12,s14,Movie,2215,Nottapon Boonprakob,Artiwara Kongmalai,Thailand,"March 1, 2019",2018,TV-MA,89 min,"Documentaries, International Movies, Sports Mo...",This intimate documentary follows rock star Ar...
13,s15,Movie,3022,John Suits,"Omar Epps, Kate Walsh, Miranda Cosgrove, Angus...",United States,"March 19, 2020",2019,R,91 min,"Independent Movies, Sci-Fi & Fantasy, Thrillers",Stranded when the Earth is suddenly destroyed ...
14,s16,Movie,Oct-01,Kunle Afolayan,"Sadiq Daba, David Bailie, Kayode Olaiya, Kehin...",Nigeria,"September 1, 2019",2014,TV-14,149 min,"Dramas, International Movies, Thrillers",Against the backdrop of Nigeria's looming inde...
15,s17,TV Show,Feb-09,NaN,"Shahd El Yaseen, Shaila Sabt, Hala, Hanadi Al-...",NaN,"March 20, 2019",2018,TV-14,1 Season,"International TV Shows, TV Dramas","As a psychology professor faces Alzheimer's, h..."
16,s18,Movie,22-Jul,Paul Greengrass,"Anders Danielsen Lie, Jon Øigarden, Jonas Stra...","Norway, Iceland, United States","October 10, 2018",2018,R,144 min,"Dramas, Thrillers","After devastating terror attacks in Norway, a ..."
17,s19,Movie,15-Aug,Swapnaneel Jayakar,"Rahul Pethe, Mrunmayee Deshpande, Adinath Koth...",India,"March 29, 2019",2019,TV-14,124 min,"Comedies, Dramas, Independent Movies","On India's Independence Day, a zany mishap in ..."
18,s20,Movie,'89,NaN,"Lee Dixon, Ian Wright, Paul Merson",United Kingdom,"May 16, 2018",2017,TV-PG,87 min,Sports Movies,"Mixing old footage with interviews, this is th..."
19,s21,Movie,​​Kuch Bheege Alfaaz,Onir,"Geetanjali Thapa, Zain Khan Durrani, Shray Rai...",India,"September 1, 2018",2018,TV-14,110 min,"Dramas, Independent Movies, International Movies",After accidentally connecting over the Interne...
20,s22,Movie,​Goli Soda 2,Vijay Milton,"Samuthirakani, Bharath Seeni, Vinoth, Esakki B...",India,"September 15, 2018",2018,TV-14,128 min,"Action & Adventure, Dramas, International Movies","A taxi driver, a gangster and an athlete strug..."
21,s23,Movie,​Maj Rati ​​Keteki,Santwana Bardoloi,"Adil Hussain, Shakil Imtiaz, Mahendra Rabha, S...",India,"September 15, 2018",2017,TV-14,117 min,"Dramas, International Movies",A successful writer returns to the town that l...
22,s24,Movie,​Mayurakshi,Atanu Ghosh,"Soumitra Chatterjee, Prasenjit Chatterjee, Ind...",India,"September 15, 2018",2017,TV-14,100 min,"Dramas, International Movies",When a middle-aged divorcee returns to Kolkata...
23,s25,TV Show,​SAINT SEIYA: Knights of the Zodiac,NaN,"Bryson Baugus, Emily Neves, Blake Shepard, Pat...",Japan,"January 23, 2020",2020,TV-14,2 Seasons,"Anime Series, International TV Shows",Seiya and the Knights of the Zodiac rise again...
24,s26,Movie,(T)ERROR,"Lyric R. Cabral, David Felix Sutcliffe",NaN,United States,"June 30, 2016",2015,NR,84 min,Documentaries,This real-life look at FBI counterterrorism op...
25,s27,TV Show,(Un)Well,NaN,NaN,United States,"August 12, 2020",2020,TV-MA,1 Season,Reality TV,This docuseries takes a deep dive into the luc...
26,s28,Movie,#Alive,Cho Il,"Yoo Ah-in, Park Shin-hye",South Korea,"September 8, 2020",2020,TV-MA,99 min,"Horror Movies, International Movies, Thrillers","As a grisly virus rampages a city, a lone man ..."
27,s29,Movie,#AnneFrank - Parallel Stories,"Sabina Fedeli, Anna Migotto","Helen Mirren, Gengher Gatti",Italy,"July 1, 2020",2019,TV-14,95 min,"Documentaries, International Movies","Through her diary, Anne Frank's story is retol..."
28,s30,TV Show,#blackAF,NaN,"Kenya Barris, Rashida Jones, Iman Benson, Genn...",United States,"April 17, 2020",2020,TV-MA,1 Season,TV Comedies,Kenya Barris and his family navigate relations...
29,s31,Movie,#cats_the_mewvie,Michael Margolis,NaN,Canada,"February 5, 2020",2020,TV-14,90 min,"Documentaries, International Movies",This pawesome documentary explores how our fel...
30,s32,Movie,#FriendButMarried,Rako Prijanto,"Adipati Dolken, Vanesha Prescilla, Rendi Jhon,...",Indonesia,"May 21, 2020",2018,TV-G,102 min,"Dramas, International Movies, Romantic Movies","Pining for his high school crush for years, a ..."
31,s33,Movie,#FriendButMarried 2,Rako Prijanto,"Adipati Dolken, Mawar de Jongh, Sari Nila, Von...",Indonesia,"June 28, 2020",2020,TV-G,104 min,"Dramas, International Movies, Romantic Movies",As Ayu and Ditto finally transition from best ...
32,s34,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...
33,s35,Movie,#Roxy,Michael Kennedy,"Jake Short, Sarah Fisher, Booboo Stewart, Dann...",Canada,"April 10, 2019",2018,TV-14,105 min,"Comedies, Romantic Movies",A teenage hacker with a huge nose helps a cool...
34,s36,Movie,#Rucker50,Robert McCullough Jr.,NaN,United States,"December 1, 2016",2016,TV-PG,56 min,"Documentaries, Sports Movies",This documentary celebrates the 50th anniversa...
35,s37,Movie,#Selfie,Cristina Jacob,"Flavia Hojda, Crina Semciuc, Olimpia Melinte, ...",Romania,"June 1, 2019",2014,TV-MA,125 min,"Comedies, Dramas, International Movies","Two days before their final exams, three teen ..."
...,...,...,...,...,...,...,...,...,...,...,...,...
1023,s1025,Movie,Boi,Jorge M. Fontana,"Bernat Quintana, Adrian Pang, Andrew Lua, Rach...",Spain,"July 26, 2019",2018,TV-MA,111 min,"Dramas, Independent Movies, International Movies",A young chauffeur who's at a crossroads in his...
1024,s1026,TV Show,BoJack Horseman,NaN,"Will Arnett, Aaron Paul, Amy Sedaris, Alison B...",United States,"October 25, 2019",2020,TV-MA,6 Seasons,TV Comedies,Meet the most beloved sitcom horse of the '90s...
1025,s1027,Movie,BoJack Horseman Christmas Special: Sabrina's C...,NaN,"Will Arnett, Aaron Paul, Alison Brie, Adam Con...",United States,"December 19, 2014",2014,TV-MA,26 min,Movies,"It's Christmas, and BoJack wants nothing to do..."
1026,s1028,Movie,Bokeh,"Geoffrey Orthwein, Andrew Sullivan","Maika Monroe, Matt O'Leary, Arnar Jónsson, Gun...","United States, Iceland","June 22, 2017",2017,TV-14,92 min,"Dramas, Independent Movies, Sci-Fi & Fantasy",After learning they are the sole survivors of ...
1027,s1029,TV Show,Bolívar,"Luis Alberto Restrepo, Andrés Beltrán, Jaime Rayo","Luis Gerónimo Abreu, José Ramón Barreto, Ernes...",Colombia,"June 21, 2019",2019,TV-MA,1 Season,"International TV Shows, Romantic TV Shows, Spa...",This dramatization depicts the life – and love...
1028,s1030,Movie,Bollywood Calling,Nagesh Kukunoor,"Om Puri, Pat Cusick, Navin Nischol, Perizaad Z...",India,"April 15, 2019",2001,TV-MA,102 min,"Comedies, Dramas, International Movies",A down-and-out Hollywood actor is utterly unpr...
1029,s1031,Movie,Bolt,"Byron Howard, Chris Williams","John Travolta, Miley Cyrus, Susie Essman, Mark...",United States,"July 22, 2018",2008,PG,99 min,"Children & Family Movies, Comedies","This tale follows German shepherd Bolt, a cani..."
1030,s1032,Movie,Bomb Scared,Borja Cobeaga,"Javier Cámara, Julián López, Miren Ibarguren, ...",Spain,"October 12, 2017",2017,TV-MA,89 min,"Comedies, Independent Movies, International Mo...","In this dark comedy, a dysfunctional group of ..."
1031,s1033,Movie,Bombairiya,Pia Sukanya,"Radhika Apte, Siddhant Kapoor, Akshay Oberoi, ...","United Arab Emirates, United Kingdom, India","March 15, 2019",2018,TV-MA,108 min,"Comedies, Dramas, International Movies","A PR agent trying to find her stolen phone, a ..."
1032,s1034,Movie,Bombay Talkies,"Anurag Kashyap, Dibakar Banerjee, Karan Johar,...","Rani Mukerji, Randeep Hooda, Saqib Saleem, Naw...",India,"July 5, 2020",2013,TV-MA,123 min,"Dramas, International Movies","A gay man deals with his sexuality, a struggli..."
1033,s1035,Movie,Bombshell,Riccardo Pilizzeri,"Ande Cunningham, Mark Mitchinson, Mia Pistoriu...",New Zealand,"October 1, 2016",2016,TV-MA,86 min,Dramas,"In 1985, when a vessel protesting nuclear test..."
1034,s1036,Movie,Bombshell: The Hedy Lamarr Story,Alexandra Dean,Hedy Lamarr,United States,"May 31, 2018",2017,TV-14,89 min,Documentaries,An unearthed audio interview of Hollywood icon...
1035,s1037,Movie,Bon Bini Holland,Jelle de Jonge,"Jandino Asporaat, Liliana de Vries, Teun Kuilb...",Netherlands,"September 1, 2016",2015,TV-MA,88 min,"Comedies, International Movies","On the island of Curaçao, an amiable scam arti..."
1036,s1038,Movie,Bon Cop Bad Cop 2,Alain Desrochers,"Patrick Huard, Colm Feore, Marc Beaupré, Noam ...",Canada,"November 11, 2017",2017,TV-MA,126 min,"Action & Adventure, Comedies, International Mo...",Two veteran buddy cops are back for a second c...
1037,s1039,Movie,"Bon Cop, Bad Cop",Erik Canuel,"Patrick Huard, Colm Feore, Sylvain Marcel, Luc...",Canada,"March 15, 2017",2006,TV-MA,117 min,"Action & Adventure, Comedies, International Mo...",An English-speaking officer from Toronto and a...
1038,s1040,TV Show,Bondi Rescue,NaN,"Andrew Günsberg, Dean Gladstone, Bruce Hopkins...",Australia,"November 1, 2019",2016,TV-PG,1 Season,Reality TV,This reality series follows elite professional...
1039,s1041,TV Show,BONDING,NaN,"Zoe Levin, Brendan Scannell, Micah Stock, Theo...",United States,"September 22, 2019",2019,TV-MA,1 Season,"TV Comedies, TV Dramas",A New York City grad student moonlighting as a...
1040,s1042,Movie,Bonnie and Clyde,Arthur Penn,"Warren Beatty, Faye Dunaway, Michael J. Pollar...",United States,"January 1, 2021",1967,R,111 min,"Action & Adventure, Classic Movies, Dramas","Bonnie Parker and Clyde Barrow are young, in l..."
1041,s1043,TV Show,Bonus Family,NaN,"Vera Vitali, Erik Johansson, Fredrik Hallgren,...",Sweden,"July 12, 2019",2019,TV-MA,3 Seasons,"International TV Shows, TV Dramas","A new couple, their exes and their children na..."
1042,s1044,TV Show,Booba,NaN,Roman Karev,Russia,"January 16, 2020",2019,TV-Y7,3 Seasons,"Kids' TV, TV Comedies",The world is a mystery to little Booba. But he...
1043,s1045,TV Show,Bookmarks,NaN,Marley Dias,United States,"September 1, 2020",2020,TV-Y,1 Season,Kids' TV,Celebrity readers share children's books by Bl...
1044,s1046,Movie,Boom,Kaizad Gustad,"Amitabh Bachchan, Gulshan Grover, Jackie Shrof...",India,"March 1, 2018",2003,TV-MA,79 min,"Action & Adventure, Dramas, International Movies","Following a fashion show mishap, three supermo..."
1045,s1047,TV Show,Border Patrol,NaN,Timothy Balme,NaN,"October 2, 2019",2016,TV-PG,1 Season,Reality TV,This reality TV series follows the men and wom...
1046,s1048,TV Show,Border Security: America's Front Line,NaN,NaN,Canada,"January 1, 2020",2018,TV-14,1 Season,"Crime TV Shows, International TV Shows, Realit...",This reality series chronicles the behind-the-...
1047,s1049,TV Show,Borderline,NaN,"David Avery, Jackie Clune, David Elms, Liz Kin...",United Kingdom,"December 2, 2017",2017,TV-14,2 Seasons,"British TV Shows, TV Comedies",A team of inept border agents tackles immigrat...
1048,s1050,TV Show,Borderliner,NaN,"Tobias Santelmann, Ellen Dorrit Petersen, Benj...","Norway, Germany, Sweden","March 6, 2018",2017,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas","To protect his family, a police detective cove..."
1049,s1051,TV Show,Bordertown,NaN,"Ville Virtanen, Matleena Kuusniemi, Anu Sinisa...","Finland, France","May 11, 2020",2019,TV-MA,3 Seasons,"Crime TV Shows, International TV Shows, TV Dramas",A gifted detective takes a job in a small town...
1050,s1052,TV Show,Borgen,NaN,"Sidse Babett Knudsen, Birgitte Hjort Sørensen,...",Denmark,"September 1, 2020",2012,TV-MA,3 Seasons,"International TV Shows, TV Dramas",A shocking turn of events puts Birgitte Nyborg...
1051,s1053,TV Show,Borges,NaN,"Thati Lopes, Antonio Pedro Tabet, Karina Ramil...",Brazil,"June 25, 2018",2018,TV-MA,1 Season,"International TV Shows, TV Comedies",Left deeply in debt after their boss flees the...
1052,s1054,Movie,Born Beautiful,Perci Intalan,"Martin del Rosario, Lou Veloso, Chai Fonacier,...",Philippines,"April 8, 2020",2019,TV-MA,96 min,"Comedies, Dramas, International Movies","After her best friend dies, Barbs attempts to ..."

In [27]:
db[:5]

,s1,TV Show,3%,Unnamed: 3,"João Miguel, Bianca Comparato, Michel Gomes, Rodolfo Valente, Vaneza Oliveira, Rafael Lozano, Viviane Porto, Mel Fronckowiak, Sergio Mamberti, Zezé Motta, Celso Frateschi",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi & Fantasy","In a future where the elite inhabit an island paradise far from the crowded slums, you get one chance to join the 3% saved from squalor."
0,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
1,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
2,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
3,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...
4,s6,TV Show,46,Serdar Akar,"Erdal Beşikçioğlu, Yasemin Allen, Melis Birkan...",Turkey,"July 1, 2017",2016,TV-MA,1 Season,"International TV Shows, TV Dramas, TV Mysteries",A genetics professor experiments with a treatm...

In [30]:
db[::4]

,s1,TV Show,3%,Unnamed: 3,"João Miguel, Bianca Comparato, Michel Gomes, Rodolfo Valente, Vaneza Oliveira, Rafael Lozano, Viviane Porto, Mel Fronckowiak, Sergio Mamberti, Zezé Motta, Celso Frateschi",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi & Fantasy","In a future where the elite inhabit an island paradise far from the crowded slums, you get one chance to join the 3% saved from squalor."
0,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
4,s6,TV Show,46,Serdar Akar,"Erdal Beşikçioğlu, Yasemin Allen, Melis Birkan...",Turkey,"July 1, 2017",2016,TV-MA,1 Season,"International TV Shows, TV Dramas, TV Mysteries",A genetics professor experiments with a treatm...
8,s10,Movie,1920,Vikram Bhatt,"Rajneesh Duggal, Adah Sharma, Indraneil Sengup...",India,"December 15, 2017",2008,TV-MA,143 min,"Horror Movies, International Movies, Thrillers",An architect and his wife move into a castle t...
12,s14,Movie,2215,Nottapon Boonprakob,Artiwara Kongmalai,Thailand,"March 1, 2019",2018,TV-MA,89 min,"Documentaries, International Movies, Sports Mo...",This intimate documentary follows rock star Ar...
16,s18,Movie,22-Jul,Paul Greengrass,"Anders Danielsen Lie, Jon Øigarden, Jonas Stra...","Norway, Iceland, United States","October 10, 2018",2018,R,144 min,"Dramas, Thrillers","After devastating terror attacks in Norway, a ..."
20,s22,Movie,​Goli Soda 2,Vijay Milton,"Samuthirakani, Bharath Seeni, Vinoth, Esakki B...",India,"September 15, 2018",2018,TV-14,128 min,"Action & Adventure, Dramas, International Movies","A taxi driver, a gangster and an athlete strug..."
24,s26,Movie,(T)ERROR,"Lyric R. Cabral, David Felix Sutcliffe",NaN,United States,"June 30, 2016",2015,NR,84 min,Documentaries,This real-life look at FBI counterterrorism op...
28,s30,TV Show,#blackAF,NaN,"Kenya Barris, Rashida Jones, Iman Benson, Genn...",United States,"April 17, 2020",2020,TV-MA,1 Season,TV Comedies,Kenya Barris and his family navigate relations...
32,s34,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...
36,s38,Movie,#Selfie 69,Cristina Jacob,"Maia Morgenstern, Olimpia Melinte, Crina Semci...",Romania,"June 1, 2019",2016,TV-MA,119 min,"Comedies, Dramas, International Movies","After a painful breakup, a trio of party-lovin..."
40,s42,Movie,Ég man þig,Óskar Thór Axelsson,"Jóhannes Haukur Jóhannesson, Ágústa Eva Erlend...",Iceland,"March 27, 2018",2017,TV-MA,106 min,"Horror Movies, International Movies","Young urbanites renovating a rundown house, an..."
44,s46,TV Show,Şubat,NaN,"Alican Yücesoy, Melisa Sözen, Musa Uzunlar, Se...",Turkey,"January 17, 2017",2013,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas",An orphan subjected to tests that gave him sup...
48,s50,Movie,10 jours en or,Nicolas Brossette,"Franck Dubosc, Claude Rich, Marie Kremer, Math...",France,"July 1, 2017",2012,TV-14,97 min,"Comedies, Dramas, International Movies",When a carefree bachelor is unexpectedly left ...
52,s54,TV Show,100 Humans,NaN,"Zainab Johnson, Sammy Obeid, Alie Ward",United States,"March 13, 2020",2020,TV-14,1 Season,"Docuseries, Science & Nature TV",One hundred hardy souls from diverse backgroun...
56,s58,Movie,100% Halal,Jastis Arimba,"Anisa Rahma, Ariyo Wahab, Anandito Dwis, Fitri...",Indonesia,"January 7, 2021",2020,TV-14,101 min,"Dramas, International Movies","After high school, a young woman marries the m..."
60,s62,TV Show,12 Years Promise,NaN,"So-yeon Lee, Namkoong Min, Tae-im Lee, So-hui ...",South Korea,"May 22, 2017",2014,TV-14,1 Season,"International TV Shows, Korean TV Shows, Roman...",A pregnant teen is forced by her family to lea...
64,s66,Movie,13 Sins,Daniel Stamm,"Mark Webber, Rutina Wesley, Devon Graye, Tom B...",United States,"January 13, 2019",2014,R,93 min,"Horror Movies, Thrillers",A man agrees to appear on a game show with a $...
68,s70,Movie,14 Cameras,"Scott Hussion, Seth Fuller","Neville Archambault, Amber Midthunder, Brytnee...",United States,"October 27, 2018",2018,TV-MA,89 min,"Horror Movies, Thrillers","Upping the “13 Cameras” ante, this sequel find..."
72,s74,Movie,18 Presents,Francesco Amato,"Vittoria Puccini, Benedetta Porcaroli, Edoardo...",Italy,"May 8, 2020",2020,TV-MA,114 min,"Dramas, Independent Movies, International Movies",A pregnant mother with terminal cancer leaves ...
76,s78,Movie,2 Alone in Paris,"Ramzy Bedia, Éric Judor","Ramzy Bedia, Éric Judor, Benoît Magimel, Krist...",France,"June 1, 2020",2008,TV-MA,97 min,"Comedies, International Movies",A bumbling Paris policeman is doggedly determi...
80,s82,Movie,2015 Dream Concert,NaN,"4Minute, B1A4, BtoB, ELSIE, EXID, EXO, Got7, I...",South Korea,"April 28, 2017",2015,TV-PG,107 min,"International Movies, Music & Musicals",The world's biggest K-pop festival marked its ...
84,s86,TV Show,21 Again,NaN,Laura Morgan,United Kingdom,"July 1, 2020",2019,TV-MA,1 Season,"British TV Shows, Reality TV","In a social experiment, a group of daughters s..."
88,s90,Movie,24 Hours to Live,Brian Smrz,"Ethan Hawke, Xu Qing, Paul Anderson, Rutger Ha...","South Africa, China, United States","April 7, 2018",2017,R,93 min,Action & Adventure,"Revived by an experimental procedure, a hit ma..."
92,s94,Movie,27: Gone Too Soon,Simon Napier-Bell,"Janis Joplin, Jimi Hendrix, Amy Winehouse, Jim...",United Kingdom,"May 1, 2018",2017,TV-MA,70 min,Documentaries,Explore the circumstances surrounding the trag...
96,s98,Movie,3 Deewarein,Nagesh Kukunoor,"Naseeruddin Shah, Jackie Shroff, Juhi Chawla, ...",NaN,"December 31, 2019",2003,TV-MA,121 min,"Dramas, International Movies, Thrillers",A reporter interviews three convicts on death ...
100,s102,Movie,3 Seconds Divorce,Shazia Javed,NaN,Canada,"June 15, 2019",2018,TV-PG,53 min,"Documentaries, Faith & Spirituality",A Muslim women's activist group in India prote...
104,s106,Movie,300 Miles to Heaven,Maciej Dejczer,"Krzysztof Stroiński, Andrzej Mellin, Adrianna ...","Denmark, France, Poland","October 1, 2019",1989,TV-14,93 min,"Dramas, International Movies","Hoping to help their dissident parents, two br..."
108,s110,Movie,40 Sticks,Victor Gatonye,"Robert Agengo, Mwaura Bilal, Andreo Kamau, Caj...",Kenya,"November 20, 2020",2019,TV-14,93 min,"International Movies, Thrillers",When their prison bus crashes in a forest on a...
112,s114,Movie,48 Christmas Wishes,"Marco Deufemia, Justin G. Dyck","Khiyla Aynne, Noah Dyer, Maya Franzoi, Clara K...",Canada,"December 20, 2017",2017,TV-G,84 min,"Children & Family Movies, Comedies",When a small town's letters to Santa accidenta...
116,s118,Movie,5 Cowok Jagoan,Anggy Umbara,"Ario Bayu, Arifin Putra, Dwi Sasono, Muhadkly ...",NaN,"January 5, 2019",2017,TV-MA,106 min,"Action & Adventure, Comedies, International Mo...",Yanto asks his friends to help save a girlfrie...
...,...,...,...,...,...,...,...,...,...,...,...,...
936,s938,Movie,Birthmarked,Emanuel Hoss-Desmarais,"Toni Collette, Matthew Goode, Andreas Apergis,...",Canada,"June 28, 2018",2018,TV-MA,88 min,"Comedies, Independent Movies, International Mo...","In an attempt to settle the ""nature vs. nurtur..."
940,s942,TV Show,Bitter Daisies,Miguel Conde,"María Mera, Toni Salgado, Miquel Insua, Denis ...",Spain,"March 29, 2019",2018,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas",While investigating the disappearance of a tee...
944,s946,Movie,Black '47,Lance Daly,"Hugo Weaving, James Frecheville, Stephen Rea, ...","Ireland, Luxembourg, Belgium","October 24, 2020",2018,R,100 min,"Action & Adventure, Dramas, Independent Movies",When the Great Famine ravages his beloved coun...
948,s950,TV Show,Black Earth Rising,NaN,"Michaela Coel, John Goodman, Abena Ayivor, Nom...",United Kingdom,"January 25, 2019",2018,TV-MA,1 Season,"British TV Shows, International TV Shows, TV D...",Adopted by a human rights attorney after the R...
952,s954,TV Show,Black Ink Crew New York,NaN,"Ceaser Emanuel, Dutchess Lattimore, Puma Robin...",United States,"December 15, 2020",2014,TV-14,2 Seasons,Reality TV,At a Black-owned-and-operated hotspot for ink ...
956,s958,Movie,Black Mirror: Bandersnatch,NaN,"Fionn Whitehead, Will Poulter, Craig Parkinson...",United States,"December 28, 2018",2018,TV-MA,312 min,"Dramas, International Movies, Sci-Fi & Fantasy","In 1984, a young programmer begins to question..."
960,s962,Movie,Black Sea,Kevin MacDonald,"Jude Law, Scoot McNairy, Ben Mendelsohn, Bobby...","United Kingdom, Russia, United States","February 16, 2019",2015,R,114 min,"Action & Adventure, Dramas, International Movies",A hard-driving submarine captain is hired to s...
964,s966,TV Show,Black Spot,NaN,"Suliane Brahim, Hubert Delattre, Laurent Capel...","France, Belgium","June 14, 2019",2019,TV-MA,2 Seasons,"Crime TV Shows, International TV Shows, TV Dramas",A police chief and an eccentric new prosecutor...
968,s970,Movie,Blackway,Daniel Alfredson,"Anthony Hopkins, Julia Stiles, Alexander Ludwi...",United States,"December 15, 2017",2015,PG-13,90 min,Thrillers,Menaced by a psychopath who's got the local co...
972,s974,TV Show,Bleach,NaN,"Masakazu Morita, Fumiko Orikasa, Yuki Matsuoka...",Japan,"April 21, 2020",2006,TV-14,5 Seasons,"Anime Series, International TV Shows",After teenager Ichigo Kurosaki acquires superp...
976,s978,Movie,Blessed Benefit,Mahmoud al Massad,"Ahmad Thaher, Maher Khammash, Odai Hijazi, Nad...","Germany, Jordan, Netherlands","October 13, 2017",2016,TV-14,83 min,"Comedies, Dramas, International Movies","After being wrongfully convicted of fraud, an ..."
980,s982,Movie,Blinky Bill: The Movie,Deane Taylor,"Ryan Kwanten, Rufus Sewell, Toni Collette, Rob...","Australia, United States","February 8, 2017",2015,PG,91 min,Children & Family Movies,Happy koala Blinky Bill and some spunky pals t...
984,s986,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"May 20, 2020",2020,TV-MA,1 Season,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
988,s990,TV Show,Blood Pact,NaN,"Guilherme Fontes, Ravel Cabral, Jonathan Haage...",Brazil,"October 10, 2018",2018,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas",An ambitious TV reporter uses risky and ethica...
992,s994,Movie,Blow,Ted Demme,"Johnny Depp, Penélope Cruz, Franka Potente, Ra...",United States,"October 1, 2019",2001,R,123 min,Dramas,Cocaine smuggler George rises from poverty to ...
996,s998,Movie,Blue Jasmine,Woody Allen,"Cate Blanchett, Sally Hawkins, Alec Baldwin, L...",United States,"March 8, 2019",2013,PG-13,98 min,"Comedies, Dramas, Independent Movies",The high life leads to high anxiety for a fash...
1000,s1002,Movie,Blue Ruin,Jeremy Saulnier,"Macon Blair, Devin Ratray, Amy Hargreaves, Kev...","United States, France","February 25, 2019",2013,R,90 min,"Independent Movies, Thrillers",Bad news from the past unhinges vagabond Dwigh...
1004,s1006,Movie,Blurred Lines: Inside the Art World,Barry Avrich,NaN,Canada,"December 31, 2017",2017,TV-MA,85 min,Documentaries,Artists and industry insiders shed light on th...
1008,s1010,Movie,Bo Burnham: what.,"Bo Burnham, Christopher Storer",Bo Burnham,United States,"July 1, 2018",2013,TV-MA,60 min,Stand-Up Comedy,Left brain and right brain duke it out – and u...
1012,s1014,Movie,Bob's Broken Sleigh,Jay Surridge,"Cole Howard, Bruce Greenwood, Victor Garber, M...",Canada,"December 17, 2015",2015,TV-G,47 min,Children & Family Movies,"An overly eager elf improves Santa's sleigh, b..."
1016,s1018,Movie,Bobby Jasoos,Samar Shaikh,"Vidya Balan, Ali Fazal, Supriya Pathak, Tanvi ...",India,"December 31, 2020",2014,TV-14,116 min,"Comedies, Dramas, International Movies",With unlimited determination and zero field ex...
1020,s1022,TV Show,Boca Juniors Confidential,NaN,NaN,NaN,"September 14, 2018",2018,TV-PG,1 Season,"Docuseries, International TV Shows, Spanish-La...","Players, fans and staff of soccer powerhouse B..."
1024,s1026,TV Show,BoJack Horseman,NaN,"Will Arnett, Aaron Paul, Amy Sedaris, Alison B...",United States,"October 25, 2019",2020,TV-MA,6 Seasons,TV Comedies,Meet the most beloved sitcom horse of the '90s...
1028,s1030,Movie,Bollywood Calling,Nagesh Kukunoor,"Om Puri, Pat Cusick, Navin Nischol, Perizaad Z...",India,"April 15, 2019",2001,TV-MA,102 min,"Comedies, Dramas, International Movies",A down-and-out Hollywood actor is utterly unpr...
1032,s1034,Movie,Bombay Talkies,"Anurag Kashyap, Dibakar Banerjee, Karan Johar,...","Rani Mukerji, Randeep Hooda, Saqib Saleem, Naw...",India,"July 5, 2020",2013,TV-MA,123 min,"Dramas, International Movies","A gay man deals with his sexuality, a struggli..."
1036,s1038,Movie,Bon Cop Bad Cop 2,Alain Desrochers,"Patrick Huard, Colm Feore, Marc Beaupré, Noam ...",Canada,"November 11, 2017",2017,TV-MA,126 min,"Action & Adventure, Comedies, International Mo...",Two veteran buddy cops are back for a second c...
1040,s1042,Movie,Bonnie and Clyde,Arthur Penn,"Warren Beatty, Faye Dunaway, Michael J. Pollar...",United States,"January 1, 2021",1967,R,111 min,"Action & Adventure, Classic Movies, Dramas","Bonnie Parker and Clyde Barrow are young, in l..."
1044,s1046,Movie,Boom,Kaizad Gustad,"Amitabh Bachchan, Gulshan Grover, Jackie Shrof...",India,"March 1, 2018",2003,TV-MA,79 min,"Action & Adventure, Dramas, International Movies","Following a fashion show mishap, three supermo..."
1048,s1050,TV Show,Borderliner,NaN,"Tobias Santelmann, Ellen Dorrit Petersen, Benj...","Norway, Germany, Sweden","March 6, 2018",2017,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas","To protect his family, a police detective cove..."
1052,s1054,Movie,Born Beautiful,Perci Intalan,"Martin del Rosario, Lou Veloso, Chai Fonacier,...",Philippines,"April 8, 2020",2019,TV-MA,96 min,"Comedies, Dramas, International Movies","After her best friend dies, Barbs attempts to ..."

In [31]:
df.index

RangeIndex(start=0, stop=1156, step=1)

In [32]:
df.columns

Index(['START_DATE*', 'END_DATE*', 'CATEGORY*', 'START*', 'STOP*', 'MILES*',
       'PURPOSE*'],
      dtype='object')

In [33]:
df['CATEGORY*']

0       Business
1       Business
2       Business
3       Business
4       Business
5       Business
6       Business
7       Business
8       Business
9       Business
10      Business
11      Business
12      Business
13      Business
14      Business
15      Business
16      Business
17      Business
18      Business
19      Business
20      Business
21      Business
22      Business
23      Business
24      Business
25      Business
26      Business
27      Business
28      Business
29      Business
          ...
1126    Business
1127    Business
1128    Business
1129    Business
1130    Business
1131    Business
1132    Business
1133    Business
1134    Business
1135    Business
1136    Business
1137    Business
1138    Business
1139    Business
1140    Business
1141    Business
1142    Business
1143    Business
1144    Business
1145    Business
1146    Business
1147    Business
1148    Business
1149    Business
1150    Business
1151    Business
1152    Business
1153    Business
1154    Business
1155         NaN
Name: CATEGORY*, Length: 1156, dtype: object

In [35]:
df['CATEGORY*'].value_counts()

Business    1078
Personal      77
Name: CATEGORY*, dtype: int64

In [36]:
df['CATEGORY*'].count()

1155

In [40]:
df.iloc[3]

START_DATE*    1/5/2016 17:31
END_DATE*      1/5/2016 17:45
CATEGORY*            Business
START*            Fort Pierce
STOP*             Fort Pierce
MILES*                    4.7
PURPOSE*              Meeting
Name: 3, dtype: object

In [41]:
df.iloc[3,3]

'Fort Pierce'

In [42]:
df.iloc[101,5]

8.9000000000000004

In [43]:
df

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
0,1/1/2016 21:11,1/1/2016 21:17,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain
1,1/2/2016 1:25,1/2/2016 1:37,Business,Fort Pierce,Fort Pierce,5.0,NaN
2,1/2/2016 20:25,1/2/2016 20:38,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies
3,1/5/2016 17:31,1/5/2016 17:45,Business,Fort Pierce,Fort Pierce,4.7,Meeting
4,1/6/2016 14:42,1/6/2016 15:49,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit
5,1/6/2016 17:15,1/6/2016 17:19,Business,West Palm Beach,West Palm Beach,4.3,Meal/Entertain
6,1/6/2016 17:30,1/6/2016 17:35,Business,West Palm Beach,Palm Beach,7.1,Meeting
7,1/7/2016 13:27,1/7/2016 13:33,Business,Cary,Cary,0.8,Meeting
8,1/10/2016 8:05,1/10/2016 8:25,Business,Cary,Morrisville,8.3,Meeting
9,1/10/2016 12:17,1/10/2016 12:44,Business,Jamaica,New York,16.5,Customer Visit
10,1/10/2016 15:08,1/10/2016 15:51,Business,New York,Queens,10.8,Meeting
11,1/10/2016 18:18,1/10/2016 18:53,Business,Elmhurst,New York,7.5,Meeting
12,1/10/2016 19:12,1/10/2016 19:32,Business,Midtown,East Harlem,6.2,Meeting
13,1/11/2016 8:55,1/11/2016 9:21,Business,East Harlem,NoMad,6.4,Temporary Site
14,1/11/2016 11:56,1/11/2016 12:03,Business,Flatiron District,Midtown,1.6,Errand/Supplies
15,1/11/2016 13:32,1/11/2016 13:46,Business,Midtown,Midtown East,1.7,Meal/Entertain
16,1/11/2016 14:30,1/11/2016 14:43,Business,Midtown East,Midtown,1.9,Meal/Entertain
17,1/12/2016 12:33,1/12/2016 12:49,Business,Midtown,Hudson Square,1.9,Meal/Entertain
18,1/12/2016 12:53,1/12/2016 13:09,Business,Hudson Square,Lower Manhattan,4.0,Meal/Entertain
19,1/12/2016 14:42,1/12/2016 14:56,Business,Lower Manhattan,Hudson Square,1.8,Errand/Supplies
20,1/12/2016 15:13,1/12/2016 15:28,Business,Hudson Square,Hell's Kitchen,2.4,Customer Visit
21,1/12/2016 15:42,1/12/2016 15:54,Business,Hell's Kitchen,Midtown,2.0,Errand/Supplies
22,1/12/2016 16:02,1/12/2016 17:00,Business,New York,Queens County,15.1,Meeting
23,1/13/2016 13:54,1/13/2016 14:07,Business,Downtown,Gulfton,11.2,Meeting
24,1/13/2016 15:00,1/13/2016 15:28,Business,Gulfton,Downtown,11.8,Meeting
25,1/14/2016 16:29,1/14/2016 17:05,Business,Houston,Houston,21.9,Customer Visit
26,1/14/2016 21:39,1/14/2016 21:45,Business,Eagan Park,Jamestown Court,3.9,Errand/Supplies
27,1/15/2016 0:41,1/15/2016 1:01,Business,Morrisville,Cary,8.0,Errand/Supplies
28,1/15/2016 11:43,1/15/2016 12:03,Business,Cary,Durham,10.4,Meal/Entertain
29,1/15/2016 13:26,1/15/2016 13:44,Business,Durham,Cary,10.4,Meal/Entertain
...,...,...,...,...,...,...,...
1126,12/28/2016 11:42,12/28/2016 12:12,Business,Unknown Location,Kar?chi,10.4,Errand/Supplies
1127,12/28/2016 13:53,12/28/2016 14:01,Business,Kar?chi,Kar?chi,2.0,Errand/Supplies
1128,12/28/2016 15:04,12/28/2016 15:39,Business,Kar?chi,Unknown Location,8.5,Meal/Entertain
1129,12/28/2016 17:02,12/28/2016 17:16,Business,Unknown Location,Kar?chi,4.4,Errand/Supplies
1130,12/28/2016 18:33,12/28/2016 18:56,Business,Kar?chi,Kar?chi,3.8,Errand/Supplies
1131,12/28/2016 22:44,12/28/2016 23:18,Business,Kar?chi,Kar?chi,5.1,Errand/Supplies
1132,12/29/2016 0:49,12/29/2016 1:06,Business,Kar?chi,Kar?chi,3.8,Errand/Supplies
1133,12/29/2016 9:44,12/29/2016 10:07,Business,Kar?chi,Unknown Location,11.6,Meal/Entertain
1134,12/29/2016 11:28,12/29/2016 12:00,Business,Unknown Location,Kar?chi,11.9,Meal/Entertain
1135,12/29/2016 12:25,12/29/2016 12:33,Business,Kar?chi,Kar?chi,1.4,Errand/Supplies
1136,12/29/2016 13:17,12/29/2016 13:24,Business,Kar?chi,Kar?chi,1.1,Errand/Supplies
1137,12/29/2016 13:56,12/29/2016 14:11,Business,Kar?chi,Kar?chi,4.1,Airport/Travel
1138,12/29/2016 14:42,12/29/2016 14:58,Business,Kar?chi,Kar?chi,6.1,Between Offices
1139,12/29/2016 15:05,12/29/2016 15:16,Business,Kar?chi,Kar?chi,1.3,Errand/Supplies
1140,12/29/2016 18:59,12/29/2016 19:14,Business,Kar?chi,Unknown Location,3.0,Meal/Entertain
1141,12/29/2016 19:50,12/29/2016 20:10,Business,Unknown Location,Kar?chi,4.1,Customer Visit
1142,12/29/2016 20:15,12/29/2016 20:45,Business,Kar?chi,Kar?chi,7.2,Meeting
1143,12/29/2016 20:53,12/29/2016 21:42,Business,Kar?chi,Unknown Location,6.4,NaN
1144,12/29/2016 23:14,12/29/2016 23:47,Business,Unknown Location,Kar?chi,12.9,Meeting
1145,12/30/2016 10:15,12/30/2016 10:33,Business,Kar?chi,Kar?chi,2.8,Errand/Supplies
1146,12/30/2016 11:31,12/30/2016 11:56,Business,Kar?chi,Kar?chi,2.9,Errand/Supplies
1147,12/30/2016 15:41,12/30/2016 16:03,Business,Kar?chi,Kar?chi,4.6,Errand/Supplies
1148,12/30/2016 16:45,12/30/2016 17:08,Business,Kar?chi,Kar?chi,4.6,Meeting
1149,12/30/2016 23:06,12/30/2016 23:10,Business,Kar?chi,Kar?chi,0.8,Customer Visit
1150,12/31/2016 1:07,12/31/2016 1:14,Business,Kar?chi,Kar?chi,0.7,Meeting
1151,12/31/2016 13:24,12/31/2016 13:42,Business,Kar?chi,Unknown Location,3.9,Temporary Site
1152,12/31/2016 15:03,12/31/2016 15:38,Business,Unknown Location,Unknown Location,16.2,Meeting
1153,12/31/2016 21:32,12/31/2016 21:50,Business,Katunayake,Gampaha,6.4,Temporary Site
1154,12/31/2016 22:08,12/31/2016 23:51,Business,Gampaha,Ilukwatta,48.2,Temporary Site
1155,Totals,NaN,NaN,NaN,NaN,12204.7,NaN